"""
كتالوج المنتجات والخدمات الرقمية لمتجر MZ
أكثر من 150 منصة وتطبيق وخدمة رقمية
برعاية ليمونة تيك (Laymouna Tech) ومنصة ماركت هب (Market Hub)
"""

CATEGORIES = {
    "cat_entertainment": {
        "title": "🎬 اشتراكات الترفيه والمشاهدة",
        "desc": "أقوى منصات الأفلام، المسلسلات، الموسيقى، والأنمي وسيرفرات القنوات والمباريات بدقة 4K.",
        "icon": "🎬",
    },
    "cat_ai_design": {
        "title": "🤖 الذكاء الاصطناعي والتصميم",
        "desc": "حسابات رسمية لأقوى أدوات الذكاء الاصطناعي، التصميم الجرافيكي، والمونتاج وهندسة الصوت.",
        "icon": "🤖",
    },
    "cat_gaming": {
        "title": "🎮 شحن الألعاب وبطاقات القيمنق",
        "desc": "شحن فوري بالآيدي (ID) لأشهر ألعاب الموبايل والكمبيوتر وبطاقات الشحن لجميع المتاجر.",
        "icon": "🎮",
    },
    "cat_software": {
        "title": "🛡️ البرامج الأصلية ومفاتيح الـ VPN",
        "desc": "مفاتيح تنشيط أصلية لأنظمة Windows، حزم Office، برامج الحماية ومكافحة الفيروسات وشبكات VPN.",
        "icon": "🛡️",
    },
    "cat_social": {
        "title": "✈️ تيلجرام وخدمات السوشيال ميديا",
        "desc": "تيلجرام بريميوم، نجوم تيلجرام، وخدمات دعم ومتابعي منصات التواصل الاجتماعي.",
        "icon": "✈️",
    },
    "cat_agency": {
        "title": "🍋 استضافات وحلول ليمونة تيك وماركت هب",
        "desc": "تأسيس المتاجر الإلكترونية، سيرفرات VPS، برمجة البوتات الذكية، وحملات التسويق الرقمي.",
        "icon": "🍋",
    },
}

SERVICES = {
    # =========================================================================
    # 1. الترفيه والمشاهدة والموسيقى (25 منصة)
    # =========================================================================
    "srv_netflix": {
        "category": "cat_entertainment",
        "name": "Netflix 4K Ultra HD",
        "icon": "🍿",
        "desc": "نتفلكس بأعلى دقة 4K UHD، مع ضمان كامل طوال فترة الاشتراك.",
        "delivery_prompt": "📧 أرسل بريدك الإلكتروني (أو رقم الواتساب) لاستلام بيانات الحساب:",
        "keywords": ["netflix", "نتفلكس", "نتفليكس", "افلام", "مسلسلات"],
        "packages": [
            {"id": "pkg_nf_1m", "name": "شاشة خاصة (شهر)", "price": "3.50$", "price_val": 3.5},
            {"id": "pkg_nf_3m", "name": "شاشة خاصة (3 شهور)", "price": "9.50$", "price_val": 9.5},
            {"id": "pkg_nf_full", "name": "حساب كامل خاص بك (شهر)", "price": "12.00$", "price_val": 12.0},
        ],
    },
    "srv_shahid": {
        "category": "cat_entertainment",
        "name": "شاهد VIP (Shahid VIP)",
        "icon": "🌟",
        "desc": "شاهد VIP الشامل للمسلسلات الحصرية، مع باقة الرياضة وقنوات البث المباشر بدقة Full HD.",
        "delivery_prompt": "📧 أرسل بريدك الإلكتروني لتفعيل الاشتراك عليه مباشرة:",
        "keywords": ["shahid", "شاهد", "مسلسلات", "vip"],
        "packages": [
            {"id": "pkg_sh_1m", "name": "اشتراك شهر كامل", "price": "3.00$", "price_val": 3.0},
            {"id": "pkg_sh_3m", "name": "اشتراك 3 شهور VIP", "price": "7.50$", "price_val": 7.5},
            {"id": "pkg_sh_1y", "name": "اشتراك سنوي كامل (12 شهر)", "price": "22.00$", "price_val": 22.0},
        ],
    },
    "srv_youtube": {
        "category": "cat_entertainment",
        "name": "YouTube Premium",
        "icon": "▶️",
        "desc": "يوتيوب بريميوم رسمي على إيميلك الشخصي: بدون إعلانات، تشغيل في الخلفية، وتحميل وتطبيق Music.",
        "delivery_prompt": "📧 أرسل إيميل حسابك في جوجل (Gmail) لإرسال دعوة التفعيل الرسمية:",
        "keywords": ["youtube", "يوتيوب", "بريميوم", "موسيقى"],
        "packages": [
            {"id": "pkg_yt_1m", "name": "اشتراك شهر واحد", "price": "2.00$", "price_val": 2.0},
            {"id": "pkg_yt_6m", "name": "اشتراك 6 شهور", "price": "8.00$", "price_val": 8.0},
            {"id": "pkg_yt_1y", "name": "اشتراك سنة كاملة", "price": "14.00$", "price_val": 14.0},
        ],
    },
    "srv_spotify": {
        "category": "cat_entertainment",
        "name": "Spotify Premium",
        "icon": "🎵",
        "desc": "ملايين الأغاني والبودكاست بأعلى جودة صوت وبدون إعلانات وبإمكانية الاستماع أوفلاين.",
        "delivery_prompt": "📧 أرسل إيميل حسابك في سبوتيفاي لتفعيله:",
        "keywords": ["spotify", "سبوتيفاي", "اغاني", "موسيقى"],
        "packages": [
            {"id": "pkg_sp_3m", "name": "اشتراك 3 شهور", "price": "5.00$", "price_val": 5.0},
            {"id": "pkg_sp_1y", "name": "اشتراك سنة كاملة", "price": "15.00$", "price_val": 15.0},
        ],
    },
    "srv_disney": {
        "category": "cat_entertainment",
        "name": "Disney+ (ديزني بلس)",
        "icon": "🏰",
        "desc": "جميع أعمال ديزني، بيكسار، مارفل، ستار وورز، وناشيونال جيوغرافيك بدقة 4K مع الترجمة والدبلجة.",
        "delivery_prompt": "📧 أرسل إيميلك أو رقم هاتفك لاستلام الحساب:",
        "keywords": ["disney", "ديزني", "مارفل"],
        "packages": [
            {"id": "pkg_dis_1m", "name": "اشتراك شهر (شاشة خاصة)", "price": "3.00$", "price_val": 3.0},
            {"id": "pkg_dis_1y", "name": "اشتراك سنة كاملة", "price": "18.00$", "price_val": 18.0},
        ],
    },
    "srv_osn": {
        "category": "cat_entertainment",
        "name": "OSN+ (أو إس إن بلس)",
        "icon": "📺",
        "desc": "المنصة الحصرية لأعمال HBO العالمية ومسلسلات بريميوم وأفلام هوليوود.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم بيانات الحساب:",
        "keywords": ["osn", "اوسن", "hbo"],
        "packages": [
            {"id": "pkg_osn_1m", "name": "اشتراك شهر كامل", "price": "3.20$", "price_val": 3.2},
            {"id": "pkg_osn_3m", "name": "اشتراك 3 شهور", "price": "8.00$", "price_val": 8.0},
        ],
    },
    "srv_prime_video": {
        "category": "cat_entertainment",
        "name": "Amazon Prime Video",
        "icon": "📦",
        "desc": "أفلام ومسلسلات أمازون برايم الأصلية بدقة فائقة مع ترجمة كاملة.",
        "delivery_prompt": "📧 أرسل بريدك الإلكتروني لاستلام الحساب:",
        "keywords": ["amazon", "prime", "امازون", "برايم"],
        "packages": [
            {"id": "pkg_prm_1m", "name": "اشتراك شهر واحد", "price": "2.50$", "price_val": 2.5},
            {"id": "pkg_prm_6m", "name": "اشتراك 6 شهور", "price": "9.00$", "price_val": 9.0},
        ],
    },
    "srv_apple_music": {
        "category": "cat_entertainment",
        "name": "Apple Music",
        "icon": "🍎",
        "desc": "أعلى جودة صوت Lossless مع ميزة الصوت المكاني Spatial Audio لجميع أجهزة أبل وأندرويد.",
        "delivery_prompt": "📧 أرسل Apple ID الخاص بك لإضافتك للباقة العائلية:",
        "keywords": ["apple", "music", "ابل ميوزك"],
        "packages": [
            {"id": "pkg_apm_3m", "name": "اشتراك 3 شهور", "price": "4.50$", "price_val": 4.5},
            {"id": "pkg_apm_1y", "name": "اشتراك سنة كاملة", "price": "14.00$", "price_val": 14.0},
        ],
    },
    "srv_deezer": {
        "category": "cat_entertainment",
        "name": "Deezer Premium",
        "icon": "🎧",
        "desc": "استمع لجميع أغانيك المفضلة بصوت HiFi فائق النقاء وبدون إعلانات.",
        "delivery_prompt": "📧 أرسل إيميل حسابك في ديزر:",
        "keywords": ["deezer", "ديزر"],
        "packages": [
            {"id": "pkg_dz_3m", "name": "اشتراك 3 شهور", "price": "4.00$", "price_val": 4.0},
        ],
    },
    "srv_anghami": {
        "category": "cat_entertainment",
        "name": "Anghami Plus (أنغامي بلس)",
        "icon": "💜",
        "desc": "تحميل واستماع لأضخم مكتبة أغاني عربية وعالمية بدون إعلانات مع ميزة كلمات الأغاني.",
        "delivery_prompt": "📱 أرسل رقم هاتفك المسجل في أنغامي أو إيميلك:",
        "keywords": ["anghami", "انغامي", "أنغامي"],
        "packages": [
            {"id": "pkg_ang_3m", "name": "اشتراك 3 شهور Plus", "price": "4.50$", "price_val": 4.5},
            {"id": "pkg_ang_1y", "name": "اشتراك سنة كاملة", "price": "13.00$", "price_val": 13.0},
        ],
    },
    "srv_tod": {
        "category": "cat_entertainment",
        "name": "TOD TV (بي إن سبورتس)",
        "icon": "⚽",
        "desc": "المنصة الرسمية لبث مباريات الدوري الإنجليزي، دوري أبطال أوروبا، والدوريات الكبرى.",
        "delivery_prompt": "📧 أرسل بريدك الإلكتروني لاستلام الحساب:",
        "keywords": ["tod", "تود", "bein", "مباريات", "كورة"],
        "packages": [
            {"id": "pkg_tod_1m", "name": "اشتراك باقة الرياضة (شهر)", "price": "7.50$", "price_val": 7.5},
        ],
    },
    "srv_bein_connect": {
        "category": "cat_entertainment",
        "name": "BeIN Connect الرسمية",
        "icon": "🏆",
        "desc": "مشاهدة قنوات beIN Sports على هاتفك أو شاشتك في أي مكان بجودة عالية.",
        "delivery_prompt": "📧 أرسل إيميلك أو رقم الواتساب لتسليم الحساب:",
        "keywords": ["bein", "بي ان", "connect"],
        "packages": [
            {"id": "pkg_bn_1m", "name": "اشتراك شهر كامل", "price": "8.00$", "price_val": 8.0},
        ],
    },
    "srv_crunchyroll": {
        "category": "cat_entertainment",
        "name": "Crunchyroll Mega Fan (أنمي)",
        "icon": "🍥",
        "desc": "أضخم منصة أنمي في العالم: أحدث الحلقات بعد ساعة من عرضها في اليابان، مترجمة وبدون إعلانات.",
        "delivery_prompt": "📧 أرسل بريدك الإلكتروني لاستلام الحساب:",
        "keywords": ["crunchyroll", "انمي", "anime", "كرانشي"],
        "packages": [
            {"id": "pkg_cr_1m", "name": "اشتراك شهر Mega Fan", "price": "2.50$", "price_val": 2.5},
            {"id": "pkg_cr_1y", "name": "اشتراك سنة كاملة", "price": "12.00$", "price_val": 12.0},
        ],
    },
    "srv_starzplay": {
        "category": "cat_entertainment",
        "name": "StarzPlay Arabia",
        "icon": "⭐",
        "desc": "مسلسلات هوليوود الحصرية وبث مباريات الدوري الإيطالي ومصارعة UFC.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام الحساب:",
        "keywords": ["starzplay", "ستارزبلاي", "ايطالي"],
        "packages": [
            {"id": "pkg_stz_1m", "name": "اشتراك شهر كامل", "price": "3.00$", "price_val": 3.0},
        ],
    },
    "srv_iptv": {
        "category": "cat_entertainment",
        "name": "سيرفر IPTV 4K للمباريات والقنوات",
        "icon": "📺",
        "desc": "أكثر من 10,000 قناة عربية وعالمية وقنوات الرياضة بدون تقطيع مع مكتبة أفلام ضخمة.",
        "delivery_prompt": "📱 أرسل نوع جهازك ورقم الواتساب لاستلام الكود والرابط:",
        "keywords": ["iptv", "سيرفر", "قنوات", "مباريات"],
        "packages": [
            {"id": "pkg_ip_3m", "name": "اشتراك 3 شهور 4K", "price": "8.00$", "price_val": 8.0},
            {"id": "pkg_ip_6m", "name": "اشتراك 6 شهور 4K", "price": "13.00$", "price_val": 13.0},
            {"id": "pkg_ip_1y", "name": "اشتراك سنة كاملة + شهرين هدية", "price": "22.00$", "price_val": 22.0},
        ],
    },
    "srv_watchit": {
        "category": "cat_entertainment",
        "name": "Watch It (ووتش إت)",
        "icon": "🇪🇬",
        "desc": "الدراما المصرية والمسلسلات الحصرية والأفلام الكلاسيكية والجديدة.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام بيانات الحساب:",
        "keywords": ["watchit", "ووتش", "مسلسلات مصرية"],
        "packages": [
            {"id": "pkg_wi_1m", "name": "اشتراك شهر", "price": "2.80$", "price_val": 2.8},
            {"id": "pkg_wi_1y", "name": "اشتراك سنوي", "price": "15.00$", "price_val": 15.0},
        ],
    },
    "srv_weyyak": {
        "category": "cat_entertainment",
        "name": "Weyyak VIP (وياك)",
        "icon": "🎬",
        "desc": "المسلسلات الهندية والتركية المدبلجة بأعلى جودة وبدون إعلانات.",
        "delivery_prompt": "📧 أرسل إيميلك للتفعيل:",
        "keywords": ["weyyak", "وياك", "هندي", "تركي"],
        "packages": [
            {"id": "pkg_wy_1m", "name": "اشتراك شهر", "price": "2.20$", "price_val": 2.2},
        ],
    },
    "srv_spacetoon": {
        "category": "cat_entertainment",
        "name": "Spacetoon Go (سبيستون غو)",
        "icon": "🚀",
        "desc": "ذكريات الطفولة وأحدث كرتون وأنمي للأطفال والشباب بدبلجة مركز الزهرة الأصلية.",
        "delivery_prompt": "📧 أرسل إيميلك لتفعيل الحساب:",
        "keywords": ["spacetoon", "سبيستون", "كرتون"],
        "packages": [
            {"id": "pkg_st_3m", "name": "اشتراك 3 شهور", "price": "4.00$", "price_val": 4.0},
            {"id": "pkg_st_1y", "name": "اشتراك سنة كاملة", "price": "11.00$", "price_val": 11.0},
        ],
    },
    "srv_soundcloud": {
        "category": "cat_entertainment",
        "name": "SoundCloud Go+",
        "icon": "☁️",
        "desc": "تحميل واستماع غير محدود لملايين الريمكسات والتراكات الحصرية أوفلاين.",
        "delivery_prompt": "📧 أرسل إيميل حسابك في ساوند كلاود:",
        "keywords": ["soundcloud", "ساوند", "كلاود"],
        "packages": [
            {"id": "pkg_sc_3m", "name": "اشتراك 3 شهور Go+", "price": "5.00$", "price_val": 5.0},
        ],
    },
    "srv_tidal": {
        "category": "cat_entertainment",
        "name": "Tidal HiFi Plus",
        "icon": "🌊",
        "desc": "أعلى نقاوة صوت لعشاق الموسيقى بدقة Master Quality Audio (MQA).",
        "delivery_prompt": "📧 أرسل إيميلك لتفعيل حساب تايدل:",
        "keywords": ["tidal", "تايدل", "hifi"],
        "packages": [
            {"id": "pkg_td_3m", "name": "اشتراك 3 شهور HiFi", "price": "4.50$", "price_val": 4.5},
        ],
    },
    "srv_hbomax": {
        "category": "cat_entertainment",
        "name": "Max (HBO Max)",
        "icon": "🐉",
        "desc": "أعمال Game of Thrones و The Last of Us وأفلام وارنر براذرز.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام الحساب:",
        "keywords": ["hbo", "max", "اتش بي او"],
        "packages": [
            {"id": "pkg_hbo_1m", "name": "اشتراك شهر خاص", "price": "3.80$", "price_val": 3.8},
        ],
    },
    "srv_hulu": {
        "category": "cat_entertainment",
        "name": "Hulu (هولو)",
        "icon": "🟢",
        "desc": "أحدث المسلسلات الأمريكية الحصرية وعروض التلفزيون المباشرة بدون إعلانات.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم الحساب:",
        "keywords": ["hulu", "هولو"],
        "packages": [
            {"id": "pkg_hu_1m", "name": "اشتراك شهر No Ads", "price": "3.50$", "price_val": 3.5},
        ],
    },
    "srv_paramount": {
        "category": "cat_entertainment",
        "name": "Paramount+ (باراماونت)",
        "icon": "⛰️",
        "desc": "أفلام باراماونت السينمائية ومسلسلات شوتايم وعروض كبرى.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام الحساب:",
        "keywords": ["paramount", "باراماونت"],
        "packages": [
            {"id": "pkg_pm_1m", "name": "اشتراك شهر", "price": "3.00$", "price_val": 3.0},
        ],
    },
    "srv_peacock": {
        "category": "cat_entertainment",
        "name": "Peacock TV Premium",
        "icon": "🦚",
        "desc": "منصة NBCUniversal: مسلسلات وأفلام وعروض WWE المباشرة.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام الحساب:",
        "keywords": ["peacock", "بي كوك", "wwe"],
        "packages": [
            {"id": "pkg_pk_1m", "name": "اشتراك شهر Premium", "price": "3.20$", "price_val": 3.2},
        ],
    },
    "srv_plex": {
        "category": "cat_entertainment",
        "name": "Plex Pass",
        "icon": "📽️",
        "desc": "سيرفر وسائط شخصي مع ميزات تنزيل أوفلاين وتخطي الشارات ومزامنة الأجهزة.",
        "delivery_prompt": "📧 أرسل إيميل حساب Plex لتفعيله:",
        "keywords": ["plex", "بليكس"],
        "packages": [
            {"id": "pkg_plx_1y", "name": "اشتراك سنة Plex Pass", "price": "14.00$", "price_val": 14.0},
        ],
    },

    # =========================================================================
    # 2. الذكاء الاصطناعي والتصميم والإنتاجية (26 منصة - تشمل Google Gemini)
    # =========================================================================
    "srv_gemini": {
        "category": "cat_ai_design",
        "name": "Google Gemini Advanced (AI)",
        "icon": "✨",
        "desc": "الاشتراك الرسمي الأقوى من جوجل: نموذج Gemini 1.5 Pro فائق الذكاء مع سعة 2TB سحابية وميزات AI في Gmail و Docs.",
        "delivery_prompt": "📧 أرسل إيميل حساب Gmail الخاص بك لإرسال دعوة التفعيل الرسمية:",
        "keywords": ["gemini", "جيميني", "جوجل", "google", "ai", "ذكاء"],
        "packages": [
            {"id": "pkg_gem_1m", "name": "اشتراك شهر تفعيل رسمي", "price": "5.50$", "price_val": 5.5},
            {"id": "pkg_gem_3m", "name": "اشتراك 3 شهور مع 2TB سحابي", "price": "14.00$", "price_val": 14.0},
        ],
    },
    "srv_chatgpt": {
        "category": "cat_ai_design",
        "name": "ChatGPT Plus (GPT-4o)",
        "icon": "🧠",
        "desc": "الوصول الكامل لأقوى نموذج من OpenAI مع توليد الصور بـ DALL-E والبرمجة وتحليل الملفات.",
        "delivery_prompt": "📧 أرسل بريدك الإلكتروني لاستلام الحساب فوراً:",
        "keywords": ["chatgpt", "gpt", "شات", "ذكاء", "openai"],
        "packages": [
            {"id": "pkg_gpt_share", "name": "حساب مشترك خاص (شهر)", "price": "6.00$", "price_val": 6.0},
            {"id": "pkg_gpt_full", "name": "حساب خاص بك بالكامل (شهر)", "price": "18.00$", "price_val": 18.0},
        ],
    },
    "srv_claude": {
        "category": "cat_ai_design",
        "name": "Claude Pro (Anthropic)",
        "icon": "🎭",
        "desc": "الذكاء الاصطناعي الأقوى في الكتابة، التحليل العميق، والبرمجة مع نموذج Claude 3.5 Sonnet.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم بيانات الحساب:",
        "keywords": ["claude", "كلود", "anthropic"],
        "packages": [
            {"id": "pkg_cld_1m", "name": "اشتراك شهر Pro", "price": "8.50$", "price_val": 8.5},
        ],
    },
    "srv_midjourney": {
        "category": "cat_ai_design",
        "name": "Midjourney AI (توليد الصور)",
        "icon": "🎨",
        "desc": "أقوى أداة في العالم لتوليد الصور والتصاميم الفنية الواقعية بالذكاء الاصطناعي.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم حساب الديسكورد المفعل:",
        "keywords": ["midjourney", "ميدجورني", "صور"],
        "packages": [
            {"id": "pkg_mj_1m", "name": "اشتراك شهر Standard Plan", "price": "11.00$", "price_val": 11.0},
        ],
    },
    "srv_canva": {
        "category": "cat_ai_design",
        "name": "Canva Pro (تفعيل رسمي)",
        "icon": "🖌️",
        "desc": "تفعيل كانفا برو الرسمي على إيميلك الشخصي: قوالب مدفوعة، إزالة الخلفيات، وخطوط حصرية.",
        "delivery_prompt": "📧 أرسل إيميل حسابك في كانفا لإرسال دعوة التفعيل الفورية:",
        "keywords": ["canva", "كانفا", "تصميم"],
        "packages": [
            {"id": "pkg_canva_1y", "name": "اشتراك سنة كاملة (12 شهر)", "price": "4.50$", "price_val": 4.5},
            {"id": "pkg_canva_life", "name": "تفعيل مدى الحياة (Lifetime)", "price": "9.00$", "price_val": 9.0},
        ],
    },
    "srv_capcut": {
        "category": "cat_ai_design",
        "name": "CapCut Pro مونتاج احترافي",
        "icon": "✂️",
        "desc": "النسخة المدفوعة من برنامج المونتاج الأشهر: تأثيرات حصرية، عزل الصوت بالذكاء الاصطناعي، و 4K 60fps.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم بيانات الحساب:",
        "keywords": ["capcut", "كابكات", "كاب كات", "مونتاج"],
        "packages": [
            {"id": "pkg_cap_1m", "name": "اشتراك شهر Pro", "price": "3.50$", "price_val": 3.5},
            {"id": "pkg_cap_1y", "name": "اشتراك سنة كاملة", "price": "16.00$", "price_val": 16.0},
        ],
    },
    "srv_adobe_all": {
        "category": "cat_ai_design",
        "name": "Adobe Creative Cloud (جميع التطبيقات)",
        "icon": "🅰️",
        "desc": "حزمة أدوبي الكاملة (Photoshop, Premiere, Illustrator, After Effects) على إيميلك الشخصي.",
        "delivery_prompt": "📧 أرسل إيميل حساب أدوبي الخاص بك للتفعيل الرسمي:",
        "keywords": ["adobe", "ادوبي", "فوتوشوب"],
        "packages": [
            {"id": "pkg_adb_1m", "name": "اشتراك شهر لجميع التطبيقات", "price": "11.00$", "price_val": 11.0},
            {"id": "pkg_adb_1y", "name": "اشتراك سنة كاملة رسمي", "price": "48.00$", "price_val": 48.0},
        ],
    },
    "srv_photoshop": {
        "category": "cat_ai_design",
        "name": "Adobe Photoshop منفرد",
        "icon": "🟦",
        "desc": "برنامج تعديل الصور الأشهر عالمياً مع ميزات Generative Fill بالذكاء الاصطناعي.",
        "delivery_prompt": "📧 أرسل إيميلك لتفعيل البرنامج:",
        "keywords": ["photoshop", "فوتوشوب"],
        "packages": [
            {"id": "pkg_ps_1y", "name": "اشتراك سنة كاملة", "price": "22.00$", "price_val": 22.0},
        ],
    },
    "srv_premiere": {
        "category": "cat_ai_design",
        "name": "Adobe Premiere Pro منفرد",
        "icon": "🎬",
        "desc": "برنامج المونتاج السينمائي الرائد لتعديل وصناعة الفيديوهات الاحترافية.",
        "delivery_prompt": "📧 أرسل إيميلك للتفعيل:",
        "keywords": ["premiere", "بريمير", "مونتاج"],
        "packages": [
            {"id": "pkg_pr_1y", "name": "اشتراك سنة كاملة", "price": "24.00$", "price_val": 24.0},
        ],
    },
    "srv_illustrator": {
        "category": "cat_ai_design",
        "name": "Adobe Illustrator منفرد",
        "icon": "🟧",
        "desc": "برنامج رسم وتصميم الفيكتور والشعارات والهويات البصرية بأعلى دقة.",
        "delivery_prompt": "📧 أرسل إيميلك للتفعيل:",
        "keywords": ["illustrator", "اليستريتور"],
        "packages": [
            {"id": "pkg_il_1y", "name": "اشتراك سنة كاملة", "price": "22.00$", "price_val": 22.0},
        ],
    },
    "srv_figma": {
        "category": "cat_ai_design",
        "name": "Figma Professional",
        "icon": "📐",
        "desc": "أداة تصميم واجهات المستخدم وتطبيقات الموبايل والمواقع (UI/UX) مع ميزات العمل الجماعي.",
        "delivery_prompt": "📧 أرسل إيميلك في فيجما لتفعيل الباقة:",
        "keywords": ["figma", "فيجما", "ui", "ux"],
        "packages": [
            {"id": "pkg_fg_1y", "name": "اشتراك سنة Professional", "price": "18.00$", "price_val": 18.0},
        ],
    },
    "srv_freepik": {
        "category": "cat_ai_design",
        "name": "Freepik Premium",
        "icon": "📷",
        "desc": "تحميل غير محدود لملايين الصور والفيكتور وقوالب PSD الاحترافية بدون علامة مائية.",
        "delivery_prompt": "📧 أرسل بريدك الإلكتروني لتسليم الحساب:",
        "keywords": ["freepik", "فري بيك", "صور"],
        "packages": [
            {"id": "pkg_fp_1m", "name": "اشتراك شهر كامل", "price": "4.00$", "price_val": 4.0},
            {"id": "pkg_fp_1y", "name": "اشتراك سنة كاملة", "price": "22.00$", "price_val": 22.0},
        ],
    },
    "srv_envato": {
        "category": "cat_ai_design",
        "name": "Envato Elements",
        "icon": "🍃",
        "desc": "المكتبة الأضخم في العالم: قوالب فيديو، مؤثرات صوتية، ثيمات ووردبريس، ورسومات برخص تجارية.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم الحساب:",
        "keywords": ["envato", "انفاتو", "elements"],
        "packages": [
            {"id": "pkg_env_1m", "name": "اشتراك شهر كامل", "price": "5.50$", "price_val": 5.5},
            {"id": "pkg_env_1y", "name": "اشتراك سنة كاملة", "price": "35.00$", "price_val": 35.0},
        ],
    },
    "srv_grammarly": {
        "category": "cat_ai_design",
        "name": "Grammarly Premium",
        "icon": "✍️",
        "desc": "تصحيح القواعد الإنجليزية، تحسين نبرة الكتابة، وإعادة صياغة النصوص باحترافية.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم الحساب:",
        "keywords": ["grammarly", "جرامرلي", "انجليزي"],
        "packages": [
            {"id": "pkg_grm_3m", "name": "اشتراك 3 شهور", "price": "5.00$", "price_val": 5.0},
            {"id": "pkg_grm_1y", "name": "اشتراك سنة كاملة", "price": "14.00$", "price_val": 14.0},
        ],
    },
    "srv_notion": {
        "category": "cat_ai_design",
        "name": "Notion Plus + AI",
        "icon": "📝",
        "desc": "أداة تنظيم المهام والمشاريع وبناء قواعد البيانات مع ميزات الذكاء الاصطناعي للكتابة والتلخيص.",
        "delivery_prompt": "📧 أرسل إيميل حسابك في Notion للتفعيل:",
        "keywords": ["notion", "نوشن", "تنظيم"],
        "packages": [
            {"id": "pkg_nt_1y", "name": "اشتراك سنة Plus + AI", "price": "15.00$", "price_val": 15.0},
        ],
    },
    "srv_duolingo": {
        "category": "cat_ai_design",
        "name": "Duolingo Super لتعلم اللغات",
        "icon": "🦉",
        "desc": "تعلم اللغات بقلوب لا نهائية، بدون إعلانات، واختبارات مخصصة لمراجعة الأخطاء.",
        "delivery_prompt": "📧 أرسل إيميل حسابك في دولينجو لتفعيله:",
        "keywords": ["duolingo", "دولينجو", "لغات"],
        "packages": [
            {"id": "pkg_duo_6m", "name": "اشتراك 6 شهور Super", "price": "5.00$", "price_val": 5.0},
            {"id": "pkg_duo_1y", "name": "اشتراك سنة كاملة", "price": "8.50$", "price_val": 8.5},
        ],
    },
    "srv_elsa": {
        "category": "cat_ai_design",
        "name": "ELSA Speak Pro (نطق الإنجليزية)",
        "icon": "🗣️",
        "desc": "مدرب ذكاء اصطناعي لتحسين مخارج الحروف والنطق الإنجليزي باللهجة الأمريكية.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم الحساب:",
        "keywords": ["elsa", "السا", "نطق"],
        "packages": [
            {"id": "pkg_els_1y", "name": "اشتراك سنة كاملة Pro", "price": "12.00$", "price_val": 12.0},
        ],
    },
    "srv_runway": {
        "category": "cat_ai_design",
        "name": "RunwayML (توليد وتعديل الفيديو AI)",
        "icon": "🎥",
        "desc": "أحدث تقنيات تحويل النص والصورة إلى فيديو احترافي مع Gen-2 و Gen-3.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم بيانات الحساب:",
        "keywords": ["runway", "رنواي", "فيديو ai"],
        "packages": [
            {"id": "pkg_rw_1m", "name": "اشتراك شهر Standard", "price": "12.50$", "price_val": 12.5},
        ],
    },
    "srv_perplexity": {
        "category": "cat_ai_design",
        "name": "Perplexity AI Pro",
        "icon": "🔍",
        "desc": "محرك البحث الذكي الأكثر دقة مع مصادر موثقة وتكامل مع Claude 3.5 و GPT-4o.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم الحساب:",
        "keywords": ["perplexity", "بيربلكسيتي", "بحث"],
        "packages": [
            {"id": "pkg_px_1y", "name": "اشتراك سنة Pro كامل", "price": "18.00$", "price_val": 18.0},
        ],
    },
    "srv_leonardo": {
        "category": "cat_ai_design",
        "name": "Leonardo.ai Premium",
        "icon": "🖌️",
        "desc": "توليد تصاميم ألعاب وصور فنية بجودة فائقة ونماذج مخصصة للرسامين.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم الحساب:",
        "keywords": ["leonardo", "ليوناردو", "رسم"],
        "packages": [
            {"id": "pkg_leo_1m", "name": "اشتراك شهر Apprentice", "price": "8.00$", "price_val": 8.0},
        ],
    },
    "srv_elevenlabs": {
        "category": "cat_ai_design",
        "name": "ElevenLabs (التعليق الصوتي AI)",
        "icon": "🎙️",
        "desc": "أكثر الأصوات البشرية واقعية للتعليق الصوتي والكتب الصوتية ودبلجة الفيديوهات.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم الحساب ورصيد الحروف:",
        "keywords": ["elevenlabs", "صوت", "فويس اوفر"],
        "packages": [
            {"id": "pkg_el_1m", "name": "اشتراك شهر Starter", "price": "4.50$", "price_val": 4.5},
            {"id": "pkg_el_creator", "name": "باقة Creator للتعليق الصوتي", "price": "16.00$", "price_val": 16.0},
        ],
    },
    "srv_quillbot": {
        "category": "cat_ai_design",
        "name": "QuillBot Premium",
        "icon": "🪶",
        "desc": "أداة إعادة الصياغة الأقوى لطلاب الجامعات والباحثين بدون حدود للكلمات.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم الحساب:",
        "keywords": ["quillbot", "كويل بوت", "صياغة"],
        "packages": [
            {"id": "pkg_qb_6m", "name": "اشتراك 6 شهور", "price": "6.00$", "price_val": 6.0},
            {"id": "pkg_qb_1y", "name": "اشتراك سنة كاملة", "price": "11.00$", "price_val": 11.0},
        ],
    },
    "srv_deepl": {
        "category": "cat_ai_design",
        "name": "DeepL Pro الترجمة الاحترافية",
        "icon": "🌐",
        "desc": "أدق محرك ترجمة في العالم يراعي السياق اللغوي وترجمة مستندات PDF و Word بالكامل.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم الحساب:",
        "keywords": ["deepl", "ديب ال", "ترجمة"],
        "packages": [
            {"id": "pkg_dp_1y", "name": "اشتراك سنة كاملة Pro", "price": "16.00$", "price_val": 16.0},
        ],
    },
    "srv_copilot": {
        "category": "cat_ai_design",
        "name": "GitHub Copilot للمطورين",
        "icon": "💻",
        "desc": "مساعد الذكاء الاصطناعي لكتابة وتصحيح الأكواد البرمجية مباشرة في VS Code.",
        "delivery_prompt": "👤 أرسل يوزر حسابك على GitHub لتفعيله:",
        "keywords": ["copilot", "كوبايلوت", "برمجة"],
        "packages": [
            {"id": "pkg_cp_6m", "name": "اشتراك 6 شهور", "price": "14.00$", "price_val": 14.0},
            {"id": "pkg_cp_1y", "name": "اشتراك سنة كاملة", "price": "24.00$", "price_val": 24.0},
        ],
    },
    "srv_cursor": {
        "category": "cat_ai_design",
        "name": "Cursor Pro AI Editor",
        "icon": "⚡",
        "desc": "محرر الأكواد الأسرع المبني بالذكاء الاصطناعي لإنجاز مشاريع البرمجة بأضعاف السرعة.",
        "delivery_prompt": "📧 أرسل إيميلك لتسليم حساب Cursor Pro:",
        "keywords": ["cursor", "كورسور", "برمجة"],
        "packages": [
            {"id": "pkg_cur_1m", "name": "اشتراك شهر Pro", "price": "14.00$", "price_val": 14.0},
        ],
    },
    "srv_google_one": {
        "category": "cat_ai_design",
        "name": "Google One سعة تخزين 2TB",
        "icon": "☁️",
        "desc": "سعة سحابية 2000GB لحسابك في Google Photos و Drive مع نسخ احتياطي وتأمين كامل.",
        "delivery_prompt": "📧 أرسل إيميل Gmail لإضافتك مباشرة:",
        "keywords": ["google", "drive", "تخزين", "جوجل"],
        "packages": [
            {"id": "pkg_go_1y", "name": "اشتراك سنة سعة 2TB", "price": "15.00$", "price_val": 15.0},
        ],
    },

    # =========================================================================
    # 3. شحن الألعاب وبطاقات القيمنق (25 منصة ولعبة)
    # =========================================================================
    "srv_pubg": {
        "category": "cat_gaming",
        "name": "شدات ببجي (PUBG Mobile UC)",
        "icon": "🔫",
        "desc": "شحن فوري بالآيدي (Player ID) فقط بدون الحاجة لكلمة المرور وبأسعار مخفضة.",
        "delivery_prompt": "🆔 أرسل رقم الآيدي (Player ID) واسم اللاعب في اللعبة:",
        "keywords": ["pubg", "ببجي", "شدات", "uc"],
        "packages": [
            {"id": "pkg_uc_60", "name": "60 شدة UC", "price": "1.10$", "price_val": 1.1},
            {"id": "pkg_uc_325", "name": "325 شدة UC (300+25)", "price": "4.80$", "price_val": 4.8},
            {"id": "pkg_uc_660", "name": "660 شدة UC (رويال باس)", "price": "9.20$", "price_val": 9.2},
            {"id": "pkg_uc_1800", "name": "1800 شدة UC", "price": "23.50$", "price_val": 23.5},
            {"id": "pkg_uc_3850", "name": "3850 شدة UC", "price": "46.00$", "price_val": 46.0},
        ],
    },
    "srv_freefire": {
        "category": "cat_gaming",
        "name": "جواهر فري فاير (Free Fire)",
        "icon": "💎",
        "desc": "شحن جواهر فري فاير الرسمي بالآيدي ومباشر في حسابك.",
        "delivery_prompt": "🆔 أرسل معرف اللاعب (Player ID) في فري فاير:",
        "keywords": ["freefire", "فري فاير", "جواهر"],
        "packages": [
            {"id": "pkg_ff_110", "name": "110 جوهرة (100+10)", "price": "1.20$", "price_val": 1.2},
            {"id": "pkg_ff_231", "name": "231 جوهرة (210+21)", "price": "2.30$", "price_val": 2.3},
            {"id": "pkg_ff_583", "name": "583 جوهرة (530+53)", "price": "5.40$", "price_val": 5.4},
            {"id": "pkg_ff_1188", "name": "1188 جوهرة (1080+108)", "price": "10.50$", "price_val": 10.5},
        ],
    },
    "srv_codm": {
        "category": "cat_gaming",
        "name": "كول أوف ديوتي (COD Mobile CP)",
        "icon": "🎖️",
        "desc": "شحن نقاط CP للعبة Call of Duty Mobile لشراء الباتل باس وسكنات الأسلحة.",
        "delivery_prompt": "🆔 أرسل UID وإيميل حساب Activision:",
        "keywords": ["cod", "كود", "كول اوف ديوتي", "cp"],
        "packages": [
            {"id": "pkg_cod_80", "name": "80 نقطة CP", "price": "1.30$", "price_val": 1.3},
            {"id": "pkg_cod_420", "name": "420 نقطة CP (باتل باس)", "price": "5.50$", "price_val": 5.5},
            {"id": "pkg_cod_880", "name": "880 نقطة CP", "price": "11.00$", "price_val": 11.0},
        ],
    },
    "srv_fortnite": {
        "category": "cat_gaming",
        "name": "فورتنايت (Fortnite V-Bucks)",
        "icon": "🦹",
        "desc": "شحن فيبوكس فورتنايت لشراء الرقصات وسكنات المتجر والباتل باس.",
        "delivery_prompt": "🆔 أرسل إيميل حساب Epic Games أو كود المنصة:",
        "keywords": ["fortnite", "فورتنايت", "فيبوكس"],
        "packages": [
            {"id": "pkg_fn_1000", "name": "1,000 V-Bucks", "price": "8.50$", "price_val": 8.5},
            {"id": "pkg_fn_2800", "name": "2,800 V-Bucks", "price": "21.00$", "price_val": 21.0},
        ],
    },
    "srv_roblox": {
        "category": "cat_gaming",
        "name": "روبلوكس (Roblox Robux)",
        "icon": "🧱",
        "desc": "شحن عملة الروبوكس الرسمية لتطوير شخصيتك وشراء الألعاب والملابس في Roblox.",
        "delivery_prompt": "👤 أرسل اسم المستخدم في روبلوكس (Username):",
        "keywords": ["roblox", "روبلوكس", "روبوكس"],
        "packages": [
            {"id": "pkg_rbx_400", "name": "400 Robux", "price": "5.50$", "price_val": 5.5},
            {"id": "pkg_rbx_800", "name": "800 Robux", "price": "10.50$", "price_val": 10.5},
            {"id": "pkg_rbx_1700", "name": "1,700 Robux", "price": "21.00$", "price_val": 21.0},
        ],
    },
    "srv_valorant": {
        "category": "cat_gaming",
        "name": "فالورانت (Valorant Points)",
        "icon": "🎯",
        "desc": "نقاط VP لشراء حزم الأسلحة وسكنات السكاكين في لعبة Valorant.",
        "delivery_prompt": "🆔 أرسل Riot ID (الاسم + الهاشتاق) وريجن الحساب:",
        "keywords": ["valorant", "فالورانت", "vp"],
        "packages": [
            {"id": "pkg_val_1000", "name": "1,000 Valorant Points", "price": "11.00$", "price_val": 11.0},
            {"id": "pkg_val_2050", "name": "2,050 Valorant Points", "price": "21.50$", "price_val": 21.5},
        ],
    },
    "srv_lol": {
        "category": "cat_gaming",
        "name": "ليق أوف ليجندز (League of Legends RP)",
        "icon": "⚔️",
        "desc": "نقاط RP لشراء الأبطال وسكنات لعبة LoL للكمبيوتر.",
        "delivery_prompt": "🆔 أرسل Riot ID وريجن السيرفر (EUW / EUNE / NA):",
        "keywords": ["lol", "league", "ليق", "ار بي"],
        "packages": [
            {"id": "pkg_lol_1380", "name": "1,380 Riot Points", "price": "12.00$", "price_val": 12.0},
        ],
    },
    "srv_brawlstars": {
        "category": "cat_gaming",
        "name": "براول ستارز (Brawl Stars Gems)",
        "icon": "🌵",
        "desc": "جواهر براول ستارز بالآيدي لشراء أبطال وسكنات براول باس.",
        "delivery_prompt": "🆔 أرسل Player Tag في لعبة Brawl Stars:",
        "keywords": ["brawl", "براول", "نجوم"],
        "packages": [
            {"id": "pkg_brw_80", "name": "80 جوهرة", "price": "5.50$", "price_val": 5.5},
            {"id": "pkg_brw_170", "name": "170 جوهرة (Brawl Pass)", "price": "11.00$", "price_val": 11.0},
        ],
    },
    "srv_clashofclans": {
        "category": "cat_gaming",
        "name": "كلاش أوف كلانس (Clash of Clans)",
        "icon": "🏰",
        "desc": "جواهر وتذكرة الميداليات الذهبية (Gold Pass) للعبة كلاش بالآيدي.",
        "delivery_prompt": "🆔 أرسل Player Tag في لعبة Clash of Clans:",
        "keywords": ["clash", "كلاش", "جواهر كلاش"],
        "packages": [
            {"id": "pkg_coc_pass", "name": "التذكرة الذهبية Gold Pass", "price": "7.50$", "price_val": 7.5},
            {"id": "pkg_coc_500", "name": "500 جوهرة", "price": "5.50$", "price_val": 5.5},
        ],
    },
    "srv_clashroyale": {
        "category": "cat_gaming",
        "name": "كلاش رويال (Clash Royale Pass)",
        "icon": "👑",
        "desc": "شحن Pass Royale وجواهر كلاش رويال المباشرة.",
        "delivery_prompt": "🆔 أرسل Player Tag في كلاش رويال:",
        "keywords": ["royale", "رويال", "كلاش رويال"],
        "packages": [
            {"id": "pkg_cr_pass", "name": "Pass Royale الذهبي", "price": "6.50$", "price_val": 6.5},
        ],
    },
    "srv_eafc": {
        "category": "cat_gaming",
        "name": "فيفا / إي إيه سبورتس (EA Sports FC Mobile)",
        "icon": "⚽",
        "desc": "نقاط FC Points لتفتيح حزم اللاعبين وبناء تشكيلة أحلامك.",
        "delivery_prompt": "🆔 أرسل UID في لعبة FC Mobile:",
        "keywords": ["fifa", "fc", "فيفا", "كوينز"],
        "packages": [
            {"id": "pkg_fc_1000", "name": "1,000 FC Points", "price": "10.50$", "price_val": 10.5},
        ],
    },
    "srv_genshin": {
        "category": "cat_gaming",
        "name": "قينشن إمباكت (Genshin Impact Crystals)",
        "icon": "✨",
        "desc": "شحن Genesis Crystals وتذكرة Welkin Moon بالآيدي والسيرفر.",
        "delivery_prompt": "🆔 أرسل UID والسيرفر (Asia / Europe / America):",
        "keywords": ["genshin", "قينشن", "جينشن"],
        "packages": [
            {"id": "pkg_gn_welkin", "name": "بركة القمر Blessing of Welkin Moon", "price": "5.50$", "price_val": 5.5},
            {"id": "pkg_gn_980", "name": "980 Genesis Crystals", "price": "16.00$", "price_val": 16.0},
        ],
    },
    "srv_mobilelegends": {
        "category": "cat_gaming",
        "name": "موبايل ليجندز (Mobile Legends)",
        "icon": "🛡️",
        "desc": "شحن ماسات Mobile Legends بالآيدي والزون (Zone ID).",
        "delivery_prompt": "🆔 أرسل معرف اللاعب (User ID) ورقم (Zone ID):",
        "keywords": ["mobile legends", "موبايل ليجند"],
        "packages": [
            {"id": "pkg_ml_277", "name": "277 ماسة داياموند", "price": "4.80$", "price_val": 4.8},
            {"id": "pkg_ml_pass", "name": "اشتراك أسبوعي Weekly Pass", "price": "2.50$", "price_val": 2.5},
        ],
    },
    "srv_ps_cards": {
        "category": "cat_gaming",
        "name": "بطاقات بلايستيشن ستور (PSN Gift Cards)",
        "icon": "🎮",
        "desc": "أكواد رقمية فورية لشحن رصيد ستور بلايستيشن (أمريكي، سعودي، إماراتي، كويتي).",
        "delivery_prompt": "🌍 حدد ريجن حسابك ورقم الواتساب لاستلام الكود الرقمي:",
        "keywords": ["psn", "playstation", "بلايستيشن", "ستور"],
        "packages": [
            {"id": "pkg_ps_10", "name": "بطاقة 10$ ستور", "price": "11.00$", "price_val": 11.0},
            {"id": "pkg_ps_25", "name": "بطاقة 25$ ستور", "price": "26.50$", "price_val": 26.5},
            {"id": "pkg_ps_50", "name": "بطاقة 50$ ستور", "price": "52.00$", "price_val": 52.0},
            {"id": "pkg_ps_100", "name": "بطاقة 100$ ستور", "price": "102.00$", "price_val": 102.0},
        ],
    },
    "srv_ps_plus": {
        "category": "cat_gaming",
        "name": "اشتراك PlayStation Plus",
        "icon": "➕",
        "desc": "اشتراكات بلس للأونلاين ومكتبة الألعاب (Essential / Extra / Deluxe).",
        "delivery_prompt": "🌍 حدد ريجن حسابك ورقم الواتساب:",
        "keywords": ["plus", "بلس", "بلايستيشن بلس"],
        "packages": [
            {"id": "pkg_psp_3m", "name": "اشتراك 3 شهور Extra", "price": "34.00$", "price_val": 34.0},
            {"id": "pkg_psp_1y", "name": "اشتراك سنة كاملة Deluxe", "price": "85.00$", "price_val": 85.0},
        ],
    },
    "srv_xbox_gamepass": {
        "category": "cat_gaming",
        "name": "Xbox Game Pass Ultimate",
        "icon": "🟢",
        "desc": "الوصول لأكثر من 400 لعبة على جهاز الإكس بوكس والكمبيوتر واللعب السحابي مع EA Play.",
        "delivery_prompt": "📧 أرسل إيميلك أو رقم الواتساب لاستلام كود التفعيل:",
        "keywords": ["xbox", "gamepass", "اكس بوكس"],
        "packages": [
            {"id": "pkg_xb_1m", "name": "اشتراك شهر Ultimate", "price": "7.50$", "price_val": 7.5},
            {"id": "pkg_xb_3m", "name": "اشتراك 3 شهور Ultimate", "price": "21.00$", "price_val": 21.0},
        ],
    },
    "srv_steam_cards": {
        "category": "cat_gaming",
        "name": "بطاقات ستيم (Steam Wallet)",
        "icon": "🕹️",
        "desc": "أكواد شحن محفظة ستيم العالمية لشراء أحدث ألعاب الكمبيوتر والإضافات.",
        "delivery_prompt": "📱 أرسل رقم الواتساب لاستلام الكود وطريقة الشحن:",
        "keywords": ["steam", "ستيم", "العاب"],
        "packages": [
            {"id": "pkg_stm_5", "name": "بطاقة 5$ ستيم عالمية", "price": "5.80$", "price_val": 5.8},
            {"id": "pkg_stm_10", "name": "بطاقة 10$ ستيم عالمية", "price": "11.20$", "price_val": 11.2},
            {"id": "pkg_stm_25", "name": "بطاقة 25$ ستيم عالمية", "price": "27.00$", "price_val": 27.0},
        ],
    },
    "srv_nintendo": {
        "category": "cat_gaming",
        "name": "بطاقات نينتندو (Nintendo eShop)",
        "icon": "🍄",
        "desc": "كروت شحن متجر Nintendo Switch لشراء ألعاب ماريو وزيلدا والبوكيمون.",
        "delivery_prompt": "📱 أرسل رقم الواتساب لاستلام الكود الرقمي:",
        "keywords": ["nintendo", "نينتندو", "سويتش"],
        "packages": [
            {"id": "pkg_nin_10", "name": "بطاقة 10$ نينتندو", "price": "11.00$", "price_val": 11.0},
            {"id": "pkg_nin_20", "name": "بطاقة 20$ نينتندو", "price": "21.50$", "price_val": 21.5},
        ],
    },
    "srv_discord_nitro": {
        "category": "cat_gaming",
        "name": "ديسكورد نيترو (Discord Nitro)",
        "icon": "👾",
        "desc": "تفعيل نيترو قيمنق: إيموجيات متحركة في كل السيرفرات، بوست سيرفر (Server Boosts)، ومشاركة شاشة بدقة 4K.",
        "delivery_prompt": "👤 أرسل رابط حسابك على ديسكورد لتفعيل الهدية المباشرة:",
        "keywords": ["discord", "nitro", "ديسكورد", "نيترو"],
        "packages": [
            {"id": "pkg_dsc_1m", "name": "اشتراك شهر كامل Nitro Gaming", "price": "4.50$", "price_val": 4.5},
            {"id": "pkg_dsc_1y", "name": "اشتراك سنة كاملة (12 شهر)", "price": "36.00$", "price_val": 36.0},
        ],
    },
    "srv_razer_gold": {
        "category": "cat_gaming",
        "name": "بطاقات رايزر جولد (Razer Gold)",
        "icon": "🪙",
        "desc": "العملة الافتراضية العالمية المعتمدة لشحن آلاف الألعاب والمنصات الترفيهية.",
        "delivery_prompt": "📱 أرسل رقم هاتفك لاستلام الكود ورقم الـ PIN:",
        "keywords": ["razer", "رايزر", "gold"],
        "packages": [
            {"id": "pkg_rz_10", "name": "بطاقة 10$ رايزر جولد عالمية", "price": "11.00$", "price_val": 11.0},
            {"id": "pkg_rz_20", "name": "بطاقة 20$ رايزر جولد عالمية", "price": "21.50$", "price_val": 21.5},
        ],
    },
    "srv_blizzard": {
        "category": "cat_gaming",
        "name": "بطاقات بليزارد (Blizzard Battle.net)",
        "icon": "❄️",
        "desc": "رصيد لشراء ألعاب World of Warcraft و Overwatch و Diablo.",
        "delivery_prompt": "📱 أرسل رقم الواتساب لاستلام الكود:",
        "keywords": ["blizzard", "بليزارد", "battlenet"],
        "packages": [
            {"id": "pkg_blz_20", "name": "بطاقة 20$ بليزارد", "price": "21.50$", "price_val": 21.5},
        ],
    },
    "srv_twitch": {
        "category": "cat_gaming",
        "name": "اشتراكات تويتش (Twitch Subs & Bits)",
        "icon": "🟣",
        "desc": "اشتراكات دعم القنوات في تويتش وإرسال البتس بأسعار مخفضة.",
        "delivery_prompt": "👤 أرسل اسم قناتك أو القناة المراد دعمها في Twitch:",
        "keywords": ["twitch", "تويتش", "بتس"],
        "packages": [
            {"id": "pkg_tw_sub", "name": "اشتراك شهر Tier 1", "price": "3.00$", "price_val": 3.0},
            {"id": "pkg_tw_1000b", "name": "1,000 Twitch Bits", "price": "11.00$", "price_val": 11.0},
        ],
    },
    "srv_itunes": {
        "category": "cat_gaming",
        "name": "بطاقات آبل وأيتونز (Apple Gift Cards)",
        "icon": "🍎",
        "desc": "لشحن حسابك وشراء التطبيقات والاشتراكات والألعاب من متجر App Store.",
        "delivery_prompt": "🌍 حدد دولة حسابك (أمريكي أو سعودي أو إماراتي) ورقم الواتساب:",
        "keywords": ["itunes", "apple", "ايتونز", "ابل"],
        "packages": [
            {"id": "pkg_itn_10", "name": "بطاقة 10$ آبل أيتونز", "price": "11.00$", "price_val": 11.0},
            {"id": "pkg_itn_25", "name": "بطاقة 25$ آبل أيتونز", "price": "26.50$", "price_val": 26.5},
            {"id": "pkg_itn_50", "name": "بطاقة 50$ آبل أيتونز", "price": "52.00$", "price_val": 52.0},
        ],
    },
    "srv_googleplay": {
        "category": "cat_gaming",
        "name": "بطاقات جوجل بلاي (Google Play Gift Cards)",
        "icon": "▶️",
        "desc": "لشحن متجر أندرويد وشراء الكتب والأفلام والجواهر داخل التطبيقات.",
        "delivery_prompt": "🌍 حدد ريجن حسابك ورقم الواتساب:",
        "keywords": ["googleplay", "جوجل بلاي"],
        "packages": [
            {"id": "pkg_gp_10", "name": "بطاقة 10$ جوجل بلاي", "price": "11.00$", "price_val": 11.0},
            {"id": "pkg_gp_25", "name": "بطاقة 25$ جوجل بلاي", "price": "26.50$", "price_val": 26.5},
        ],
    },
    "srv_apex": {
        "category": "cat_gaming",
        "name": "إيبكس ليجندز (Apex Legends Coins)",
        "icon": "🏹",
        "desc": "عملات Apex Coins لشراء الباتل باس وحزم الأسلحة والشخصيات.",
        "delivery_prompt": "🆔 أرسل منصتك (PC / Console) وإيميل EA:",
        "keywords": ["apex", "ايبكس", "ابكس"],
        "packages": [
            {"id": "pkg_apx_1000", "name": "1,000 Apex Coins", "price": "10.50$", "price_val": 10.5},
        ],
    },

    # =========================================================================
    # 4. البرامج الأصلية، الحماية، وشبكات الـ VPN (25 برنامج)
    # =========================================================================
    "srv_windows11": {
        "category": "cat_software",
        "name": "مفتاح Windows 11 Pro أصلي",
        "icon": "🪟",
        "desc": "مفتاح رقمي رسمي أصلي 100% يرتبط بجهازك مدى الحياة مع كامل التحديثات الأمنية.",
        "delivery_prompt": "💻 أرسل رقم الواتساب أو الإيميل لاستلام المفتاح مع خطوات التنشيط السهلة:",
        "keywords": ["windows", "ويندوز", "ويندوز 11"],
        "packages": [
            {"id": "pkg_w11_pro", "name": "مفتاح Windows 11 Pro أصلي (مدى الحياة)", "price": "4.50$", "price_val": 4.5},
        ],
    },
    "srv_windows10": {
        "category": "cat_software",
        "name": "مفتاح Windows 10 Pro أصلي",
        "icon": "🪟",
        "desc": "مفتاح رقمي رسمي دائم لجهازك ويدعم الترقية المجانية إلى Windows 11.",
        "delivery_prompt": "💻 أرسل رقم الواتساب أو الإيميل لاستلام المفتاح:",
        "keywords": ["windows 10", "ويندوز 10"],
        "packages": [
            {"id": "pkg_w10_pro", "name": "مفتاح Windows 10 Pro أصلي (مدى الحياة)", "price": "4.00$", "price_val": 4.0},
        ],
    },
    "srv_win_server": {
        "category": "cat_software",
        "name": "Windows Server 2022 / 2025 Standard",
        "icon": "🖥️",
        "desc": "ترخيص سيرفرات مايكروسوفت الرسمية للمؤسسات والشركات والمطورين.",
        "delivery_prompt": "📧 أرسل بريدك الإلكتروني لاستلام المفتاح والشهادة:",
        "keywords": ["server", "سيرفر", "ويندوز سيرفر"],
        "packages": [
            {"id": "pkg_srv_2022", "name": "ترخيص Windows Server Standard رسمي", "price": "18.00$", "price_val": 18.0},
        ],
    },
    "srv_office365": {
        "category": "cat_software",
        "name": "Microsoft Office 365 Pro + 1TB",
        "icon": "📑",
        "desc": "حساب رسمي مفعل مدى الحياة يدعم 5 أجهزة مع سعة تخزينية 1TB على OneDrive.",
        "delivery_prompt": "📧 أرسل إيميلك أو رقم هاتفك لاستلام بيانات الدخول والتعليمات:",
        "keywords": ["office", "اوفيس", "365", "word", "excel"],
        "packages": [
            {"id": "pkg_off_pro", "name": "حساب Office 365 كامل (5 أجهزة)", "price": "6.00$", "price_val": 6.0},
        ],
    },
    "srv_office2021": {
        "category": "cat_software",
        "name": "Office 2021 Professional Plus",
        "icon": "📊",
        "desc": "مفتاح رقمي دائم يرتبط بحساب مايكروسوفت الخاص بك لجهاز كمبيوتر واحد.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام مفتاح التنشيط:",
        "keywords": ["office 2021", "اوفيس 2021"],
        "packages": [
            {"id": "pkg_off_21", "name": "مفتاح تفعيل أصلي دائم", "price": "7.50$", "price_val": 7.5},
        ],
    },
    "srv_office2024": {
        "category": "cat_software",
        "name": "Office 2024 Pro الجديد",
        "icon": "📈",
        "desc": "النسخة الأحدث والأسرع من أوفيس مع أحدث واجهات إكسل ووورد وباوربوينت.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام الكود:",
        "keywords": ["office 2024", "اوفيس 2024"],
        "packages": [
            {"id": "pkg_off_24", "name": "مفتاح تفعيل رسمي دائم", "price": "11.00$", "price_val": 11.0},
        ],
    },
    "srv_kaspersky": {
        "category": "cat_software",
        "name": "Kaspersky Total Security / Plus",
        "icon": "🛡️",
        "desc": "الحماية الأقوى عالمياً ضد الفيروسات، برامج الفدية، وحماية المعاملات البنكية.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام مفتاح التنشيط لسنة كاملة:",
        "keywords": ["kaspersky", "كاسبر", "حماية", "انتي فايروس"],
        "packages": [
            {"id": "pkg_ksp_1y1d", "name": "ترخيص سنة كاملة (جهاز واحد)", "price": "8.00$", "price_val": 8.0},
            {"id": "pkg_ksp_1y3d", "name": "ترخيص سنة كاملة (3 أجهزة)", "price": "14.00$", "price_val": 14.0},
        ],
    },
    "srv_norton": {
        "category": "cat_software",
        "name": "Norton 360 Deluxe",
        "icon": "🔒",
        "desc": "حماية شاملة ضد الاختراق مع جدار حماية قوي وتأمين الكاميرا والـ VPN.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام الكود:",
        "keywords": ["norton", "نورتون"],
        "packages": [
            {"id": "pkg_nrt_1y", "name": "اشتراك سنة (3 أجهزة)", "price": "9.50$", "price_val": 9.5},
        ],
    },
    "srv_bitdefender": {
        "category": "cat_software",
        "name": "Bitdefender Total Security",
        "icon": "🛡️",
        "desc": "أعلى تقييم أمني في اختبارات الحماية مع استهلاك منخفض لموارد المعالج والرام.",
        "delivery_prompt": "📧 أرسل إيميلك للتفعيل:",
        "keywords": ["bitdefender", "بت ديفندر"],
        "packages": [
            {"id": "pkg_bit_1y", "name": "اشتراك سنة كاملة (5 أجهزة)", "price": "11.00$", "price_val": 11.0},
        ],
    },
    "srv_eset": {
        "category": "cat_software",
        "name": "ESET NOD32 Internet Security",
        "icon": "🤖",
        "desc": "البرنامج الأخف وزناً والأسرع في فحص الملفات وحماية الألعاب والتصفح.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام المفتاح:",
        "keywords": ["eset", "ايسيت", "nod32"],
        "packages": [
            {"id": "pkg_est_1y", "name": "ترخيص سنة كاملة", "price": "8.50$", "price_val": 8.5},
        ],
    },
    "srv_mcafee": {
        "category": "cat_software",
        "name": "McAfee Total Protection",
        "icon": "🔴",
        "desc": "حماية متعددة الأجهزة تشمل مكافحة التجسس وحماية الهوية الرقمية.",
        "delivery_prompt": "📧 أرسل إيميلك للتفعيل:",
        "keywords": ["mcafee", "مكافي"],
        "packages": [
            {"id": "pkg_mcf_1y", "name": "اشتراك سنة كاملة", "price": "7.00$", "price_val": 7.0},
        ],
    },
    "srv_malwarebytes": {
        "category": "cat_software",
        "name": "Malwarebytes Premium",
        "icon": "🦠",
        "desc": "المتخصص الأول في القضاء على برمجيات التجسس الخبيثة والإعلانات المزعجة.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام الكود:",
        "keywords": ["malwarebytes", "مالوير"],
        "packages": [
            {"id": "pkg_mlw_1y", "name": "اشتراك سنة كاملة", "price": "9.00$", "price_val": 9.0},
        ],
    },
    "srv_nordvpn": {
        "category": "cat_software",
        "name": "NordVPN فائق السرعة",
        "icon": "🌐",
        "desc": "أسرع وأشهر شبكة VPN في العالم: حماية الخصوصية، تشفير عالي، وفتح المواقع المحجوبة.",
        "delivery_prompt": "📧 أرسل بريدك الإلكتروني لاستلام الحساب المفعل:",
        "keywords": ["nordvpn", "vpn", "نورد", "بروكسي"],
        "packages": [
            {"id": "pkg_nrd_6m", "name": "اشتراك 6 شهور", "price": "9.00$", "price_val": 9.0},
            {"id": "pkg_nrd_1y", "name": "اشتراك سنة كاملة", "price": "16.00$", "price_val": 16.0},
        ],
    },
    "srv_expressvpn": {
        "category": "cat_software",
        "name": "ExpressVPN",
        "icon": "🚀",
        "desc": "سيرفرات في أكثر من 90 دولة وبدون أي تسجيل للبيانات لسرعة قياسية وأمان مطلق.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام كود التفعيل:",
        "keywords": ["expressvpn", "اكسبراس", "vpn"],
        "packages": [
            {"id": "pkg_exp_3m", "name": "اشتراك 3 شهور", "price": "12.00$", "price_val": 12.0},
            {"id": "pkg_exp_1y", "name": "اشتراك سنة كاملة", "price": "28.00$", "price_val": 28.0},
        ],
    },
    "srv_surfshark": {
        "category": "cat_software",
        "name": "Surfshark VPN",
        "icon": "🦈",
        "desc": "اتصال غير محدود لعدد لا نهائي من الأجهزة وحظر الإعلانات المدمج CleanWeb.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام الحساب:",
        "keywords": ["surfshark", "سيرفشارك", "vpn"],
        "packages": [
            {"id": "pkg_srf_1y", "name": "اشتراك سنة كاملة", "price": "14.00$", "price_val": 14.0},
        ],
    },
    "srv_cyberghost": {
        "category": "cat_software",
        "name": "CyberGhost VPN",
        "icon": "👻",
        "desc": "سيرفرات متخصصة للبث المباشر والألعاب وتحميل التورنت بسرعة عالية.",
        "delivery_prompt": "📧 أرسل إيميلك للتسليم:",
        "keywords": ["cyberghost", "سايبر"],
        "packages": [
            {"id": "pkg_cbg_1y", "name": "اشتراك سنة كاملة", "price": "12.00$", "price_val": 12.0},
        ],
    },
    "srv_protonvpn": {
        "category": "cat_software",
        "name": "ProtonVPN Plus سويسري",
        "icon": "🛡️",
        "desc": "أقوى حماية للخصوصية بموجب القوانين السويسرية الصارمة بدون أي تتبع.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام الحساب:",
        "keywords": ["proton", "بروتون", "vpn"],
        "packages": [
            {"id": "pkg_prt_1y", "name": "اشتراك سنة Plus", "price": "18.00$", "price_val": 18.0},
        ],
    },
    "srv_windscribe": {
        "category": "cat_software",
        "name": "Windscribe VPN Pro",
        "icon": "💨",
        "desc": "جدار ناري لحجب كل أنواع التتبع والتسريب مع سيرفرات في أكثر من 60 دولة.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام الحساب:",
        "keywords": ["windscribe", "ويندسcribe"],
        "packages": [
            {"id": "pkg_wnd_1y", "name": "اشتراك سنة Pro", "price": "13.00$", "price_val": 13.0},
        ],
    },
    "srv_idm": {
        "category": "cat_software",
        "name": "Internet Download Manager (IDM)",
        "icon": "⚡",
        "desc": "تفعيل برنامج التحميل الأسرع مدى الحياة برقم تسلسلي رسمي رسمي يرتبط باسمك.",
        "delivery_prompt": "📧 أرسل اسمك بالإنجليزية وإيميلك لاستلام السيريال الرسمي:",
        "keywords": ["idm", "داونلود", "تحميل"],
        "packages": [
            {"id": "pkg_idm_life", "name": "مفتاح رسمي أصلي مدى الحياة", "price": "11.00$", "price_val": 11.0},
        ],
    },
    "srv_winrar": {
        "category": "cat_software",
        "name": "رخصة WinRAR أصلية",
        "icon": "📦",
        "desc": "رخصة تجارية رسمية مدى الحياة لإزالة رسالة التنبيه المزعجة وضغط الملفات بأمان.",
        "delivery_prompt": "📧 أرسل اسمك وإيميلك لتسجيل الرخصة:",
        "keywords": ["winrar", "وينرار", "ضغط"],
        "packages": [
            {"id": "pkg_rar_life", "name": "رخصة دائمة أصلية", "price": "6.00$", "price_val": 6.0},
        ],
    },
    "srv_vmware": {
        "category": "cat_software",
        "name": "VMware Workstation Pro",
        "icon": "💾",
        "desc": "برنامج تشغيل الأنظمة الوهمية الأقوى للمطورين والمخترقين الأخلاقيين وخبراء الشبكات.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام كود التفعيل:",
        "keywords": ["vmware", "انظمة وهمية"],
        "packages": [
            {"id": "pkg_vmw_life", "name": "مفتاح تنشيط دائم Pro", "price": "9.50$", "price_val": 9.5},
        ],
    },
    "srv_parallels": {
        "category": "cat_software",
        "name": "Parallels Desktop لأجهزة Mac",
        "icon": "🍎",
        "desc": "تشغيل نظام Windows وبرامج الكمبيوتر على أجهزة الماك وشاشات Apple Silicon بسلاسة تامة.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام ترخيص التفعيل:",
        "keywords": ["parallels", "باراليلز", "ماك"],
        "packages": [
            {"id": "pkg_par_life", "name": "ترخيص تفعيل دائم Pro", "price": "16.00$", "price_val": 16.0},
        ],
    },
    "srv_cleanmymac": {
        "category": "cat_software",
        "name": "CleanMyMac X الأصلي",
        "icon": "🧹",
        "desc": "تنظيف وتسريع أجهزة الماك وحذف الملفات المؤقتة وإلغاء تثبيت البرامج بالكامل.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام مفتاح التنشيط:",
        "keywords": ["cleanmymac", "تنظيف ماك"],
        "packages": [
            {"id": "pkg_cmm_life", "name": "ترخيص أصلي لجهاز ماك واحد", "price": "14.00$", "price_val": 14.0},
        ],
    },
    "srv_adguard": {
        "category": "cat_software",
        "name": "AdGuard Premium (حظر الإعلانات)",
        "icon": "🚫",
        "desc": "حظر كامل لجميع أنواع الإعلانات والنوافذ المنبثقة في التطبيقات والمواقع لجميع أجهزتك.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام كود التفعيل الرسمي:",
        "keywords": ["adguard", "حظر اعلانات"],
        "packages": [
            {"id": "pkg_adg_life", "name": "ترخيص مدى الحياة (3 أجهزة)", "price": "8.50$", "price_val": 8.5},
        ],
    },
    "srv_ccleaner": {
        "category": "cat_software",
        "name": "CCleaner Professional",
        "icon": "🧽",
        "desc": "تنظيف الريجستري وتسريع إقلاع الويندوز وتحديث البرامج التلقائي.",
        "delivery_prompt": "📧 أرسل إيميلك لاستلام السيريال:",
        "keywords": ["ccleaner", "تنظيف ويندوز"],
        "packages": [
            {"id": "pkg_cc_1y", "name": "ترخيص سنة كاملة Pro", "price": "6.00$", "price_val": 6.0},
        ],
    },

    # =========================================================================
    # 5. تيلجرام والسوشيال ميديا (25 خدمة)
    # =========================================================================
    "srv_tg_prem_3m": {
        "category": "cat_social",
        "name": "تيلجرام بريميوم (3 شهور)",
        "icon": "⭐",
        "desc": "تفعيل رسمي إهداء بدون باسورد: شارة النجمة، سرعة مضاعفة، وتحويل الصوت لنص.",
        "delivery_prompt": "👤 أرسل يوزر حسابك على تيلجرام (مثال: @username):",
        "keywords": ["telegram", "تيلجرام", "بريميوم"],
        "packages": [
            {"id": "pkg_tgp_3", "name": "اشتراك 3 شهور بريميوم", "price": "10.50$", "price_val": 10.5},
        ],
    },
    "srv_tg_prem_6m": {
        "category": "cat_social",
        "name": "تيلجرام بريميوم (6 شهور)",
        "icon": "⭐",
        "desc": "تفعيل رسمي إهداء بدون باسورد لمدة 6 شهور كاملة.",
        "delivery_prompt": "👤 أرسل يوزر حسابك على تيلجرام (مثال: @username):",
        "keywords": ["telegram 6m", "تيلجرام 6 شهور"],
        "packages": [
            {"id": "pkg_tgp_6", "name": "اشتراك 6 شهور بريميوم", "price": "17.00$", "price_val": 17.0},
        ],
    },
    "srv_tg_prem_1y": {
        "category": "cat_social",
        "name": "تيلجرام بريميوم (سنة كاملة)",
        "icon": "⭐",
        "desc": "تفعيل رسمي إهداء بدون باسورد لمدة 12 شهر كاملة مع توفير كبير.",
        "delivery_prompt": "👤 أرسل يوزر حسابك على تيلجرام (مثال: @username):",
        "keywords": ["telegram 1y", "تيلجرام سنة"],
        "packages": [
            {"id": "pkg_tgp_12", "name": "اشتراك 12 شهر بريميوم", "price": "29.00$", "price_val": 29.0},
        ],
    },
    "srv_tg_stars": {
        "category": "cat_social",
        "name": "شحن نجوم تيلجرام (Telegram Stars)",
        "icon": "🌟",
        "desc": "شحن عملة النجوم لشراء المنتجات الرقمية ودعم القنوات وصناع المحتوى.",
        "delivery_prompt": "👤 أرسل يوزر حسابك على تيلجرام:",
        "keywords": ["stars", "نجوم", "نجوم تيلجرام"],
        "packages": [
            {"id": "pkg_str_250", "name": "250 نجمة تيلجرام", "price": "5.50$", "price_val": 5.5},
            {"id": "pkg_str_500", "name": "500 نجمة تيلجرام", "price": "10.50$", "price_val": 10.5},
            {"id": "pkg_str_1000", "name": "1,000 نجمة تيلجرام", "price": "20.00$", "price_val": 20.0},
        ],
    },
    "srv_tg_members": {
        "category": "cat_social",
        "name": "أعضاء قنوات ومجموعات تيلجرام",
        "icon": "👥",
        "desc": "تزويد سريع وثابت لأعضاء القنوات والمجموعات لرفع الثقة والانتشار.",
        "delivery_prompt": "🔗 أرسل رابط القناة أو المجموعة العامة:",
        "keywords": ["اعضاء", "اعضاء تيلجرام", "قنوات"],
        "packages": [
            {"id": "pkg_tgm_1k", "name": "1,000 عضو قناة جودة عالية", "price": "3.00$", "price_val": 3.0},
            {"id": "pkg_tgm_5k", "name": "5,000 عضو قناة جودة عالية", "price": "13.00$", "price_val": 13.0},
        ],
    },
    "srv_tg_views": {
        "category": "cat_social",
        "name": "مشاهدات منشورات تيلجرام",
        "icon": "👁️",
        "desc": "مشاهدات حقيقية للمنشورات والرسائل في قنوات تيلجرام لزيادة التفاعل.",
        "delivery_prompt": "🔗 أرسل رابط المنشور المراد تزويده:",
        "keywords": ["مشاهدات تيلجرام"],
        "packages": [
            {"id": "pkg_tgv_10k", "name": "10,000 مشاهدة منشور", "price": "2.00$", "price_val": 2.0},
        ],
    },
    "srv_ig_followers": {
        "category": "cat_social",
        "name": "متابعين إنستغرام جودة عالية",
        "icon": "📸",
        "desc": "متابعين حسابات حقيقية مع ضمان عدم النقصان وتوصيل سريع وآمن 100%.",
        "delivery_prompt": "🔗 أرسل رابط حسابك على إنستغرام (تأكد أن الحساب عام وليس خاص):",
        "keywords": ["instagram", "انستغرام", "متابعين انستا"],
        "packages": [
            {"id": "pkg_igf_1k", "name": "1,000 متابع حقيقي", "price": "2.50$", "price_val": 2.5},
            {"id": "pkg_igf_5k", "name": "5,000 متابع حقيقي", "price": "10.00$", "price_val": 10.0},
            {"id": "pkg_igf_10k", "name": "10,000 متابع مع ضمان تعويض", "price": "18.50$", "price_val": 18.5},
        ],
    },
    "srv_ig_likes": {
        "category": "cat_social",
        "name": "لايكات إنستغرام فورية",
        "icon": "❤️",
        "desc": "لايكات سريعة للمنشورات والصور لرفع التفاعل وخوارزميات الإكسبلور.",
        "delivery_prompt": "🔗 أرسل رابط المنشور:",
        "keywords": ["لايكات انستا", "لايكات"],
        "packages": [
            {"id": "pkg_igl_1k", "name": "1,000 لايك إنستغرام", "price": "1.20$", "price_val": 1.2},
            {"id": "pkg_igl_5k", "name": "5,000 لايك إنستغرام", "price": "4.50$", "price_val": 4.5},
        ],
    },
    "srv_ig_reels": {
        "category": "cat_social",
        "name": "مشاهدات إنستغرام ريلز (Reels)",
        "icon": "🎬",
        "desc": "مشاهدات عالية السرعة لريلز إنستغرام لزيادة فرص الصعود للتريند.",
        "delivery_prompt": "🔗 أرسل رابط فيديو الريلز:",
        "keywords": ["ريلز", "مشاهدات ريلز"],
        "packages": [
            {"id": "pkg_igr_10k", "name": "10,000 مشاهدة ريلز", "price": "1.50$", "price_val": 1.5},
            {"id": "pkg_igr_50k", "name": "50,000 مشاهدة ريلز", "price": "5.00$", "price_val": 5.0},
        ],
    },
    "srv_ig_comments": {
        "category": "cat_social",
        "name": "تعليقات إنستغرام مخصصة",
        "icon": "💬",
        "desc": "تعليقات عربية إيجابية مخصصة أو عشوائية تزيد مصداقية المتجر والمنتج.",
        "delivery_prompt": "🔗 أرسل رابط المنشور مع التعليقات المقترحة:",
        "keywords": ["تعليقات انستا", "كومنتات"],
        "packages": [
            {"id": "pkg_igc_50", "name": "50 تعليق عربي مخصص", "price": "3.50$", "price_val": 3.5},
        ],
    },
    "srv_tiktok_followers": {
        "category": "cat_social",
        "name": "متابعين تيك توك حقيقيين",
        "icon": "🎵",
        "desc": "زيادة متابعين تيك توك لتفعيل ميزات البث المباشر (LIVE) وزيادة الانتشار.",
        "delivery_prompt": "🔗 أرسل رابط حسابك على تيك توك:",
        "keywords": ["tiktok", "تيك توك", "متابعين تيك توك"],
        "packages": [
            {"id": "pkg_tkf_1k", "name": "1,000 متابع تيك توك (تفعيل اللايف)", "price": "4.00$", "price_val": 4.0},
            {"id": "pkg_tkf_5k", "name": "5,000 متابع تيك توك", "price": "18.00$", "price_val": 18.0},
        ],
    },
    "srv_tiktok_likes": {
        "category": "cat_social",
        "name": "لايكات تيك توك سريعة",
        "icon": "❤️",
        "desc": "قلوب وتفاعل سريع لفيديوهات التيك توك لمضاعفة ظهورها في For You.",
        "delivery_prompt": "🔗 أرسل رابط الفيديو في تيك توك:",
        "keywords": ["لايكات تيك توك"],
        "packages": [
            {"id": "pkg_tkl_1k", "name": "1,000 لايك تيك توك", "price": "1.50$", "price_val": 1.5},
            {"id": "pkg_tkl_5k", "name": "5,000 لايك تيك توك", "price": "6.00$", "price_val": 6.0},
        ],
    },
    "srv_tiktok_views": {
        "category": "cat_social",
        "name": "مشاهدات تيك توك بالملايين",
        "icon": "🚀",
        "desc": "ملايين المشاهدات الفورية لفيديوهات التيك توك بأرخص الأسعار.",
        "delivery_prompt": "🔗 أرسل رابط الفيديو:",
        "keywords": ["مشاهدات تيك توك"],
        "packages": [
            {"id": "pkg_tkv_100k", "name": "100,000 مشاهدة تيك توك", "price": "2.00$", "price_val": 2.0},
            {"id": "pkg_tkv_1m", "name": "1,000,000 مشاهدة (مليون)", "price": "8.00$", "price_val": 8.0},
        ],
    },
    "srv_tiktok_coins": {
        "category": "cat_social",
        "name": "شحن عملات تيك توك (TikTok Coins)",
        "icon": "🪙",
        "desc": "شحن عملات كوينز تيك توك لدعم البثوث وإرسال الهدايا بأسعار أقل من المتجر.",
        "delivery_prompt": "👤 أرسل يوزر حساب تيك توك مع رقم الواتساب:",
        "keywords": ["عملات تيك توك", "كوينز"],
        "packages": [
            {"id": "pkg_tkc_700", "name": "700 عملة تيك توك", "price": "9.50$", "price_val": 9.5},
            {"id": "pkg_tkc_1400", "name": "1,400 عملة تيك توك", "price": "18.50$", "price_val": 18.5},
        ],
    },
    "srv_x_followers": {
        "category": "cat_social",
        "name": "متابعين منصة إكس / تويتر",
        "icon": "✖️",
        "desc": "متابعين جودة عالية لحسابات تويتر لزيادة الثقة والمكانة الرقمية.",
        "delivery_prompt": "🔗 أرسل رابط حسابك على منصة X:",
        "keywords": ["twitter", "تويتر", "منصة x"],
        "packages": [
            {"id": "pkg_xf_1k", "name": "1,000 متابع X", "price": "5.00$", "price_val": 5.0},
        ],
    },
    "srv_x_retweets": {
        "category": "cat_social",
        "name": "إعادة تغريد ورتويت X",
        "icon": "🔁",
        "desc": "رتويت وإعجابات للتغريدات لرفعها للتريند وزيادة مدى وصولها.",
        "delivery_prompt": "🔗 أرسل رابط التغريدة:",
        "keywords": ["رتويت", "لايكات تويتر"],
        "packages": [
            {"id": "pkg_xr_500", "name": "500 رتويت حقيقي", "price": "3.50$", "price_val": 3.5},
        ],
    },
    "srv_x_premium": {
        "category": "cat_social",
        "name": "اشتراك X Premium (العلامة الزرقاء)",
        "icon": "🔷",
        "desc": "توثيق حسابك بالعلامة الزرقاء، تعديل التغريدات، وتفعيل أرباح الإعلانات.",
        "delivery_prompt": "👤 أرسل يوزر حسابك على X ورقم الواتساب:",
        "keywords": ["توثيق تويتر", "العلامة الزرقاء"],
        "packages": [
            {"id": "pkg_xp_1m", "name": "اشتراك شهر Premium", "price": "9.50$", "price_val": 9.5},
        ],
    },
    "srv_snap_followers": {
        "category": "cat_social",
        "name": "متابعين سناب شات للملف التعريفي",
        "icon": "👻",
        "desc": "متابعين حقيقيين لملف السناب العام (Public Profile).",
        "delivery_prompt": "🔗 أرسل رابط ملفك في سناب شات:",
        "keywords": ["snapchat", "سناب", "سناب شات"],
        "packages": [
            {"id": "pkg_snf_1k", "name": "1,000 متابع سناب شات", "price": "6.00$", "price_val": 6.0},
        ],
    },
    "srv_snap_views": {
        "category": "cat_social",
        "name": "مشاهدات ستوري سناب شات",
        "icon": "👁️",
        "desc": "رفع مشاهدات الستوري اليومي والقصص في سناب شات.",
        "delivery_prompt": "👤 أرسل يوزر حسابك على سناب:",
        "keywords": ["مشاهدات سناب"],
        "packages": [
            {"id": "pkg_snv_1k", "name": "1,000 مشاهدة ستوري", "price": "3.00$", "price_val": 3.0},
        ],
    },
    "srv_yt_subs": {
        "category": "cat_social",
        "name": "مشتركين قنوات يوتيوب",
        "icon": "🔴",
        "desc": "مشتركين ثابتين لقنوات اليوتيوب لتفعيل شروط تحقيق الدخل والربح.",
        "delivery_prompt": "🔗 أرسل رابط قناتك على يوتيوب:",
        "keywords": ["مشتركين يوتيوب", "يوتيوب"],
        "packages": [
            {"id": "pkg_yts_500", "name": "500 مشترك يوتيوب ثابت", "price": "7.00$", "price_val": 7.0},
            {"id": "pkg_yts_1k", "name": "1,000 مشترك يوتيوب ثابت (شرط الربح)", "price": "13.00$", "price_val": 13.0},
        ],
    },
    "srv_yt_watchhours": {
        "category": "cat_social",
        "name": "ساعات مشاهدة يوتيوب (4000 ساعة)",
        "icon": "⏱️",
        "desc": "تحقيق ساعات المشاهدة الـ 4000 الرسمية لتفعيل تحقيق الدخل في YouTube Studio.",
        "delivery_prompt": "🔗 أرسل رابط القناة (يشترط وجود فيديو مدته ساعة فأكثر):",
        "keywords": ["ساعات يوتيوب", "4000 ساعة"],
        "packages": [
            {"id": "pkg_ytw_4k", "name": "باقة 4,000 ساعة مشاهدة كاملة ومضمونة", "price": "38.00$", "price_val": 38.0},
        ],
    },
    "srv_fb_followers": {
        "category": "cat_social",
        "name": "متابعين صفحات فيسبوك",
        "icon": "📘",
        "desc": "متابعين وإعجابات لصفحات الأعمال والمتاجر في فيسبوك.",
        "delivery_prompt": "🔗 أرسل رابط صفحة الفيسبوك:",
        "keywords": ["facebook", "فيسبوك", "متابعين فيسبوك"],
        "packages": [
            {"id": "pkg_fbf_1k", "name": "1,000 متابع صفحة فيسبوك", "price": "2.80$", "price_val": 2.8},
        ],
    },
    "srv_fb_likes": {
        "category": "cat_social",
        "name": "لايكات وتفاعل فيسبوك",
        "icon": "👍",
        "desc": "لايكات ورياكشنات متنوعة (Love, Care, Wow) لمنشورات الفيسبوك.",
        "delivery_prompt": "🔗 أرسل رابط المنشور:",
        "keywords": ["لايكات فيسبوك"],
        "packages": [
            {"id": "pkg_fbl_1k", "name": "1,000 لايك منشور", "price": "1.50$", "price_val": 1.5},
        ],
    },
    "srv_google_reviews": {
        "category": "cat_social",
        "name": "تقييمات خرائط جوجل (5 نجوم)",
        "icon": "🌟",
        "desc": "تقييمات ومراجعات حقيقية 5 نجوم لنشاطك التجاري على خرائط Google Maps ترفع ترتيبك وتزيد الزبائن.",
        "delivery_prompt": "📍 أرسل رابط موقع نشاطك على خرائط جوجل:",
        "keywords": ["تقييمات خرائط جوجل", "google maps"],
        "packages": [
            {"id": "pkg_ggr_10", "name": "10 تقييمات 5 نجوم مع نص عربي إيجابي", "price": "8.00$", "price_val": 8.0},
            {"id": "pkg_ggr_25", "name": "25 تقييم 5 نجوم لرفع السمعة", "price": "18.00$", "price_val": 18.0},
        ],
    },
    "srv_verification": {
        "category": "cat_social",
        "name": "استشارة توثيق الحسابات بالعلامة الزرقاء",
        "icon": "✔️",
        "desc": "تجهيز ملف التوثيق الصحفي والمقالات الإخبارية لتوثيق إنستغرام وفيسبوك.",
        "delivery_prompt": "📞 أرسل رابط حسابك ورقم الواتساب لمراجعة الأهلية:",
        "keywords": ["توثيق", "علامة زرقاء"],
        "packages": [
            {"id": "pkg_ver_audit", "name": "فحص وتجهيز ملف التوثيق الرسمي", "price": "25.00$", "price_val": 25.0},
        ],
    },

    # =========================================================================
    # 6. استضافات وحلول ليمونة تيك وماركت هب (25 خدمة)
    # =========================================================================
    "srv_salla_store": {
        "category": "cat_agency",
        "name": "تأسيس متجر سلة (Salla)",
        "icon": "🛒",
        "desc": "تصميم وتجهيز متجر احترافي على منصة سلة السعودية: ثيم فخم، ربط بوابات الدفع، وترتيب الأقسام.",
        "delivery_prompt": "📞 أرسل اسم متجرك ورقم الواتساب لمناقشة الخطة:",
        "keywords": ["سلة", "salla", "متجر سلة"],
        "packages": [
            {"id": "pkg_sal_setup", "name": "باقة تأسيس وتصميم متجر سلة كامل", "price": "75.00$", "price_val": 75.0},
        ],
    },
    "srv_zid_store": {
        "category": "cat_agency",
        "name": "تأسيس متجر زد (Zid)",
        "icon": "🏬",
        "desc": "تجهيز وتخصيص متجر متكامل على منصة زد مع شركات الشحن وطرق الدفع.",
        "delivery_prompt": "📞 أرسل رقم الواتساب للتواصل ومناقشة تفاصيل المتجر:",
        "keywords": ["زد", "zid", "متجر زد"],
        "packages": [
            {"id": "pkg_zid_setup", "name": "باقة تأسيس متجر زد الاحترافي", "price": "80.00$", "price_val": 80.0},
        ],
    },
    "srv_shopify_store": {
        "category": "cat_agency",
        "name": "متجر شوبيفاي عالمي (Shopify)",
        "icon": "🛍️",
        "desc": "بناء متجر شوبيفاي للتجارة الدولية والدروب شيبينغ مع ثيم مدفوع وسرعة عالية.",
        "delivery_prompt": "📞 أرسل رقم هاتفك وفكرة المتجر:",
        "keywords": ["shopify", "شوبيفاي", "دروبشيبينغ"],
        "packages": [
            {"id": "pkg_shp_setup", "name": "تصميم متجر شوبيفاي متكامل مع ثيم مدفوع", "price": "95.00$", "price_val": 95.0},
        ],
    },
    "srv_woostore": {
        "category": "cat_agency",
        "name": "متجر ووكومرس مخصص (WooCommerce)",
        "icon": "🟣",
        "desc": "متجر حر بالكامل على ووردبريس بدون رسوم شهرية وبكامل السيطرة على البيانات.",
        "delivery_prompt": "📞 أرسل رقم هاتفك لمناقشة متطلبات المتجر:",
        "keywords": ["woocommerce", "ووكومرس", "ووردبريس"],
        "packages": [
            {"id": "pkg_woo_setup", "name": "برمجة متجر ووكومرس متكامل وسريع", "price": "110.00$", "price_val": 110.0},
        ],
    },
    "srv_domain_reg": {
        "category": "cat_agency",
        "name": "حجز وشراء نطاق (.com / .net / .store)",
        "icon": "🌐",
        "desc": "حجز وتجديد الدومين الرسمي لاسم شركتك أو متجرك مع حماية الخصوصية وربطه بموقعك.",
        "delivery_prompt": "✍️ أرسل اسم الدومين المقترح للتحقق من توفره:",
        "keywords": ["domain", "دومين", "نطاق"],
        "packages": [
            {"id": "pkg_dom_1y", "name": "حجز دومين .com لمدة سنة كاملة", "price": "12.00$", "price_val": 12.0},
        ],
    },
    "srv_cloud_host": {
        "category": "cat_agency",
        "name": "استضافة مواقع سحابية NVMe فائقة السرعة",
        "icon": "⚡",
        "desc": "استضافة ووردبريس سحابية فائقة السرعة مع شهادة أمان SSL مجانية وإيميلات رسمية.",
        "delivery_prompt": "🌐 أرسل اسم موقعك أو دومينك للتجهيز:",
        "keywords": ["استضافة", "سيرفر", "hosting"],
        "packages": [
            {"id": "pkg_hst_1y", "name": "خطة استضافة سحابية سنوية (مساحة 25GB)", "price": "35.00$", "price_val": 35.0},
        ],
    },
    "srv_vps_server": {
        "category": "cat_agency",
        "name": "سيرفرات سحابية خاصة (Cloud VPS)",
        "icon": "🖥️",
        "desc": "سيرفر VPS خاص للمشاريع البرمجية والمتاجر الكبرى مع وصول كامل Root Access.",
        "delivery_prompt": "💻 أرسل المواصفات المطلوبة ورقم الواتساب:",
        "keywords": ["vps", "سيرفر vps"],
        "packages": [
            {"id": "pkg_vps_1m", "name": "خطة VPS (4 Core / 8GB RAM / 100GB SSD)", "price": "18.00$", "price_val": 18.0},
        ],
    },
    "srv_biz_email": {
        "category": "cat_agency",
        "name": "إيميلات رسمية للشركات (Business Email)",
        "icon": "📧",
        "desc": "بريد إلكتروني رسمي باسم شركتك (info@yourcompany.com) يرفع مصداقيتك أمام العملاء.",
        "delivery_prompt": "🌐 أرسل اسم دومين شركتك ورقم الواتساب:",
        "keywords": ["ايميل رسمي", "business email"],
        "packages": [
            {"id": "pkg_eml_5", "name": "باقة 5 إيميلات رسمية لمدة سنة", "price": "15.00$", "price_val": 15.0},
        ],
    },
    "srv_workspace": {
        "category": "cat_agency",
        "name": "Google Workspace للشركات",
        "icon": "💼",
        "desc": "إيميل شركة رسمي مدمج مع Gmail وسعة Google Drive و Google Meet للشركات.",
        "delivery_prompt": "🌐 أرسل دومين الشركة للتفعيل:",
        "keywords": ["workspace", "وركسبيس", "جوجل شركات"],
        "packages": [
            {"id": "pkg_gws_1y", "name": "حساب سنوي مفعل للشركة", "price": "32.00$", "price_val": 32.0},
        ],
    },
    "srv_wp_themes": {
        "category": "cat_agency",
        "name": "قوالب ووردبريس بريميوم مرخصة (Astra / Divi)",
        "icon": "🎨",
        "desc": "قوالب تصميم مواقع أصلية برخصة رسمية وتحديثات أوتوماتيكية مدى الحياة.",
        "delivery_prompt": "🌐 أرسل رابط موقعك لتفعيل القالب:",
        "keywords": ["قوالب ووردبريس", "astra", "divi"],
        "packages": [
            {"id": "pkg_thm_pro", "name": "تفعيل قالب Astra Pro أو Divi مدى الحياة", "price": "9.50$", "price_val": 9.5},
        ],
    },
    "srv_elementor": {
        "category": "cat_agency",
        "name": "إضافة Elementor Pro لتصميم المواقع",
        "icon": "🧱",
        "desc": "أشهر أداة لتصميم وتطوير صفحات المواقع والمتاجر بالسحب والإفلات برخصة رسمية.",
        "delivery_prompt": "🌐 أرسل رابط موقعك لتفعيل مفتاح الترخيص:",
        "keywords": ["elementor", "المنتو", "اليمنتور"],
        "packages": [
            {"id": "pkg_elm_1y", "name": "ترخيص رسمي Elementor Pro لمدة سنة", "price": "8.00$", "price_val": 8.0},
        ],
    },
    "srv_wprocket": {
        "category": "cat_agency",
        "name": "إضافة تسريع المواقع WP Rocket",
        "icon": "🚀",
        "desc": "أقوى إضافة كاش وضغط ملفات لجعل موقعك يفتح في أقل من ثانية في Google PageSpeed.",
        "delivery_prompt": "🌐 أرسل رابط موقعك للتفعيل:",
        "keywords": ["wprocket", "تسريع موقع"],
        "packages": [
            {"id": "pkg_wpr_1y", "name": "ترخيص سنوي رسمي WP Rocket", "price": "7.50$", "price_val": 7.5},
        ],
    },
    "srv_tg_bot_dev": {
        "category": "cat_agency",
        "name": "برمجة بوت تيلجرام مخصص (ليمونة تيك)",
        "icon": "🤖",
        "desc": "برمجة بوت ذكي متكامل لمتجرك أو خدمتك أو نظامك الإداري مع ربط قواعد بيانات واستضافة 24/7.",
        "delivery_prompt": "✍️ أرسل فكرة البوت المطلوبة ورقم الواتساب للتواصل التقني:",
        "keywords": ["برمجة بوت", "تيلجرام بوت", "ليمونة"],
        "packages": [
            {"id": "pkg_tgb_custom", "name": "باقة برمجة وتهيئة بوت متكامل", "price": "75.00$", "price_val": 75.0},
        ],
    },
    "srv_wa_bot_dev": {
        "category": "cat_agency",
        "name": "شات بوت واتساب للأعمال (WhatsApp Bot)",
        "icon": "💬",
        "desc": "أتمتة الرد على استفسارات العملاء وأخذ الطلبات وإرسال الفواتير آلياً عبر الواتساب.",
        "delivery_prompt": "📞 أرسل رقم نشاطك ورقم الواتساب لمناقشة الربط:",
        "keywords": ["شات بوت واتساب", "whatsapp bot"],
        "packages": [
            {"id": "pkg_wab_custom", "name": "برمجة وربط نظام واتساب للأعمال", "price": "85.00$", "price_val": 85.0},
        ],
    },
    "srv_make_zapier": {
        "category": "cat_agency",
        "name": "أتمتة العمليات والربط (Make / Zapier)",
        "icon": "⚡",
        "desc": "ربط متجرك بجداول Google Sheets، برامج المحاسبة، وأنظمة CRM لنقل البيانات آلياً.",
        "delivery_prompt": "📞 أرسل تفاصيل الأنظمة المطلوب ربطها:",
        "keywords": ["zapier", "make", "اتمته"],
        "packages": [
            {"id": "pkg_mk_setup", "name": "باقة ربط وتكامل مسارات العمل", "price": "45.00$", "price_val": 45.0},
        ],
    },
    "srv_branding": {
        "category": "cat_agency",
        "name": "تصميم هوية بصرية وشعار (Logo & Branding)",
        "icon": "🎨",
        "desc": "تصميم شعار احترافي، ألوان الهوية، بطاقات الأعمال، وقوالب السوشيال ميديا لمشروعك.",
        "delivery_prompt": "📞 أرسل اسم نشاطك ورؤيتك للتصميم:",
        "keywords": ["لوجو", "شعار", "هوية بصرية"],
        "packages": [
            {"id": "pkg_brd_full", "name": "باقة الهوية البصرية المتكاملة للمشاريع", "price": "55.00$", "price_val": 55.0},
        ],
    },
    "srv_banners": {
        "category": "cat_agency",
        "name": "تصميم بنرات وسلايدرات متجر إلكتروني",
        "icon": "🖼️",
        "desc": "تصاميم بنرات عروض ترويجية بياعة وجذابة متوافقة مع متجر سلة وزد وشوبيفاي.",
        "delivery_prompt": "🛒 أرسل رابط متجرك ورقم الواتساب:",
        "keywords": ["بنرات", "تصميم بنرات"],
        "packages": [
            {"id": "pkg_bnr_3", "name": "تصميم 3 بنرات احترافية للمتجر", "price": "20.00$", "price_val": 20.0},
        ],
    },
    "srv_meta_ads_mng": {
        "category": "cat_agency",
        "name": "إدارة حملات إعلانات ميتا (إنستغرام وفيسبوك)",
        "icon": "🎯",
        "desc": "إدارة احترافية للحملات الممولة لاستهداف الجمهور المشتري ورفع مبيعات متجرك.",
        "delivery_prompt": "📞 أرسل رابط حساب نشاطك ورقم الواتساب:",
        "keywords": ["اعلانات ممولة", "اعلانات انستا", "تسويق"],
        "packages": [
            {"id": "pkg_adm_1m", "name": "إدارة حملات إعلانية شهرية متكاملة", "price": "90.00$", "price_val": 90.0},
        ],
    },
    "srv_tiktok_ads_mng": {
        "category": "cat_agency",
        "name": "إدارة إعلانات تيك توك وسناب شات",
        "icon": "📱",
        "desc": "إطلاق وإدارة إعلانات الفيديو والتيك توك وسناب شات لأسواق الخليج والوطن العربي.",
        "delivery_prompt": "📞 أرسل رقم الواتساب لمناقشة الحملة:",
        "keywords": ["اعلانات تيك توك", "اعلانات سناب"],
        "packages": [
            {"id": "pkg_adt_1m", "name": "إدارة وتوسيع حملات تيك توك وسناب", "price": "95.00$", "price_val": 95.0},
        ],
    },
    "srv_google_ads_mng": {
        "category": "cat_agency",
        "name": "إدارة إعلانات جوجل واليوتيوب (Google Ads)",
        "icon": "🔍",
        "desc": "تصدر نتائج بحث جوجل الأول واستهداف العملاء الباحثين عن خدماتك بدقة.",
        "delivery_prompt": "📞 أرسل رابط موقعك ومجال عملك:",
        "keywords": ["اعلانات جوجل", "google ads"],
        "packages": [
            {"id": "pkg_adg_1m", "name": "إدارة حملات شبكة بحث جوجل ويوتيوب", "price": "100.00$", "price_val": 100.0},
        ],
    },
    "srv_seo": {
        "category": "cat_agency",
        "name": "تهيئة محركات البحث (SEO)",
        "icon": "📈",
        "desc": "تحسين صفحات موقعك وظهورها مجاناً في الصفحات الأولى في جوجل بدون إعلانات.",
        "delivery_prompt": "🌐 أرسل رابط موقعك لفحصه:",
        "keywords": ["seo", "سيو", "تصدر جوجل"],
        "packages": [
            {"id": "pkg_seo_1m", "name": "خطة تحسين سيو شهرية On-Page و Off-Page", "price": "70.00$", "price_val": 70.0},
        ],
    },
    "srv_copywriting": {
        "category": "cat_agency",
        "name": "كتابة نصوص إعلانية ووصف منتجات بياع",
        "icon": "✍️",
        "desc": "صياغة نصوص تسويقية مقنعة تحفز العميل على النقر والشراء الفوري.",
        "delivery_prompt": "🛒 أرسل تفاصيل منتجك أو خدمتك:",
        "keywords": ["كتابة محتوى", "copywriting"],
        "packages": [
            {"id": "pkg_cpy_pack", "name": "باقة 5 نصوص إعلانية بياعة + خطة إطلاق", "price": "25.00$", "price_val": 25.0},
        ],
    },
    "srv_gplay_dev": {
        "category": "cat_agency",
        "name": "حساب مطور جوجل بلاي (Google Play Console)",
        "icon": "🤖",
        "desc": "تجهيز وتفعيل حساب مطور رسمي لنشر تطبيقاتك وألعابك على متجر جوجل بلاي.",
        "delivery_prompt": "📧 أرسل إيميلك ورقم هاتفك:",
        "keywords": ["google play console", "حساب مطور"],
        "packages": [
            {"id": "pkg_gpd_acc", "name": "تجهيز وتفعيل حساب مطور Google Play", "price": "38.00$", "price_val": 38.0},
        ],
    },
    "srv_apple_dev": {
        "category": "cat_agency",
        "name": "حساب مطور أبل (Apple Developer)",
        "icon": "🍏",
        "desc": "مساعدة في إنشاء وتفعيل اشتراك Apple Developer السنوي لنشر تطبيقات iOS.",
        "delivery_prompt": "📞 أرسل رقم الواتساب للتواصل:",
        "keywords": ["apple developer", "مطور ابل"],
        "packages": [
            {"id": "pkg_apd_acc", "name": "استشارة وتجهيز حساب مطور أبل", "price": "40.00$", "price_val": 40.0},
        ],
    },
    "srv_laymouna_consult": {
        "category": "cat_agency",
        "name": "استشارة تقنية شاملة من ليمونة تيك",
        "icon": "🍋",
        "desc": "جلسة استشارية خاصة لمدة 45 دقيقة عبر Google Meet لمراجعة فكرة مشروعك واختيار أفضل بنية برمجية.",
        "delivery_prompt": "📞 أرسل رقم الواتساب لتحديد موعد الجلسة الاستشارية:",
        "keywords": ["استشارة", "ليمونة تيك", "استشارات تقنية"],
        "packages": [
            {"id": "pkg_cns_session", "name": "جلسة استشارية 45 دقيقة + تقرير توصيات", "price": "25.00$", "price_val": 25.0},
        ],
    },
}

PAYMENT_METHODS = [
    {"id": "pay_wallet", "name": "📱 محفظة إلكترونية (CliQ / فودافون كاش / زين كاش / STC Pay)"},
    {"id": "pay_crypto", "name": "💎 عملات رقمية (USDT - TRC20 / Binance Pay)"},
    {"id": "pay_bank", "name": "🏦 تحويل بنكي مباشر"},
    {"id": "pay_card", "name": "💳 بطاقة فيزا / ماستر كارد / بايبال"},
]
